const mongoose=require('mongoose');const axios=require('axios');const {Telegraf,Markup}=require('telegraf');
const FB='https://5sim.net/v1';
const TOKEN=process.env.FIVESIM_API_KEY||process.env.FIVE_SIM_API_KEY||process.env['5SIM_API_KEY']||'';
const enc=x=>encodeURIComponent(String(x));const dec=x=>{try{return decodeURIComponent(x)}catch{return String(x)}};const num=x=>{const v=Number(x);return Number.isFinite(v)?v:0};
async function cfg(){try{return await mongoose.connection.db.collection('number_server_configs').findOne({server:'5sim'})}catch{return null}}
async function rate(){try{const x=await mongoose.connection.db.collection('settings').findOne({key:'usdtInrRate'});const v=num(x?.value);return v>0?v:100}catch{return 100}}
async function prices(country,service){return(await axios.get(FB+'/guest/prices',{params:{country,product:service},timeout:20000,headers:{Accept:'application/json'}})).data}
function block(raw,country,service){return raw?.[country]?.[service]||raw?.[String(country).toLowerCase()]?.[service]||null}
function ops(raw,country,service){const b=block(raw,country,service);if(!b||typeof b!=='object')return[];return Object.entries(b).map(([operator,v])=>({operator,price:num(v?.cost??v?.price??v?.rate),stock:num(v?.count??v?.stock??v?.qty??v?.quantity??v?.available)})).filter(x=>x.price>0||x.stock>0)}
function sell(raw,c,rr){let p=num(raw)*rr;const fixed=num(c?.profit??c?.profitAmount),pct=num(c?.profitPercent??c?.markup);if(fixed>0)p+=fixed;if(pct>0)p*=1+pct/100;return Math.ceil(p*100)/100}
async function buy5(bot,uid,country,service,operator){const User=mongoose.models.User,user=await User?.findOne({userId:String(uid)});if(!user)return bot.telegram.sendMessage(uid,'❌ User not found.');if(user.banned)return bot.telegram.sendMessage(uid,'❌ You are banned.');if(user.activeOrder)return bot.telegram.sendMessage(uid,'⚠️ You already have an active order.\n\nPlease complete or cancel it first.');let raw;try{raw=await prices(country,service)}catch{return bot.telegram.sendMessage(uid,'❌ Live price/stock fetch failed. Please try again.')}const b=block(raw,country,service),o=b?.[operator];if(!o)return bot.telegram.sendMessage(uid,'❌ Selected operator is no longer available. Please try again.');const stock=num(o.count??o.stock??o.qty??o.quantity??o.available);if(stock<=0)return bot.telegram.sendMessage(uid,'❌ Selected operator is out of stock.');const c=await cfg(),rr=await rate(),price=sell(o.cost??o.price??o.rate,c,rr);if(num(user.credits)<price)return bot.telegram.sendMessage(uid,`❌ Not enough credits\n\nRequired: ${price}\nBalance: ${num(user.credits)}`);if(!TOKEN)return bot.telegram.sendMessage(uid,'❌ Server 3 API is not configured.');let order;try{order=(await axios.get(FB+`/user/buy/activation/${enc(country)}/${enc(operator)}/${enc(service)}`,{headers:{Authorization:`Bearer ${TOKEN}`,Accept:'application/json'},timeout:20000})).data}catch(e){return bot.telegram.sendMessage(uid,`❌ Server 3 error\n\n${e.response?.data?.message||e.response?.data?.error||e.message}`)}if(!order?.id||!order?.phone)return bot.telegram.sendMessage(uid,'❌ Number is not available from the selected operator right now.');user.credits=num(user.credits)-price;user.activeOrder=true;user.activeOrderId='5s:'+order.id;await user.save();return bot.telegram.sendMessage(uid,`╔══════════════════════╗\n 📱 NUMBER ALLOCATED\n╚══════════════════════╝\n\n🖥 Server : 3\n🌍 Country : ${country}\n✅ Service : ${service.toUpperCase()}\n📡 Operator : ${order.operator||operator}\n📱 Number : <code>${order.phone}</code>\n🆔 Order ID : <code>${order.id}</code>\n\n💎 Price : ${price} credits`,{parse_mode:'HTML',...Markup.inlineKeyboard([[Markup.button.callback('❌ Cancel',`ns_cancel_5s_${order.id}_${price}`)],[Markup.button.callback('🔄 Check OTP',`ns_otp_5s_${order.id}_${service}_${price}`)],[Markup.button.callback('🏠 Home','home')]])})}
const prev=Telegraf.prototype.handleUpdate;Telegraf.prototype.handleUpdate=async function(u,...args){try{const q=u?.callback_query,cb=q?.data||'',uid=q?.from?.id;if(q&&uid&&cb.startsWith('fbuy:5sim:')){const z=cb.split(':'),country=dec(z[2]),service=dec(z.slice(3).join(':'));try{await this.telegram.answerCbQuery(q.id)}catch{};let raw;try{raw=await prices(country,service)}catch(e){console.log('5SIM LIVE OPERATOR FETCH:',e.response?.data||e.message);return this.telegram.editMessageText(q.message.chat.id,q.message.message_id,undefined,'❌ Live operator price/stock fetch failed.\n\nPlease try again.',Markup.inlineKeyboard([[Markup.button.callback('⬅ Countries','fsearch:5sim')]]))}const a=ops(raw,country,service),c=await cfg(),rr=await rate();if(!a.length)return this.telegram.editMessageText(q.message.chat.id,q.message.message_id,undefined,`⚠️ Confirm Number\n\n🖥 Server : 3\n📦 Service: ${service}\n🌍 Country: ${country}\n\n❌ No operator is currently available.`,Markup.inlineKeyboard([[Markup.button.callback('⬅ Countries','fsearch:5sim')]]));const rows=a.map(o=>[Markup.button.callback(`📡 ${o.operator} • ₹${sell(o.price,c,rr)} • Stock: ${o.stock}`,'5op:'+enc(country)+':'+enc(service)+':'+enc(o.operator))]);rows.push([Markup.button.callback('❌ Decline','5decline')]);return this.telegram.editMessageText(q.message.chat.id,q.message.message_id,undefined,`⚠️ Confirm Number\n\n🖥 Server : 3\n📦 Service: ${service}\n🌍 Country: ${country}\n\n💰 Live operator pricing:\n${a.map(o=>`• ${o.operator} | ₹${sell(o.price,c,rr)} | Stock: ${o.stock}`).join('\n')}\n\nSelect an operator below.`,Markup.inlineKeyboard(rows))}
if(q&&uid&&cb.startsWith('5op:')){const z=cb.split(':'),country=dec(z[1]),service=dec(z[2]),operator=dec(z.slice(3).join(':'));try{await this.telegram.answerCbQuery(q.id)}catch{};let raw;try{raw=await prices(country,service)}catch{return this.telegram.editMessageText(q.message.chat.id,q.message.message_id,undefined,'❌ Live price fetch failed. Please try again.')}const o=block(raw,country,service)?.[operator];if(!o)return this.telegram.editMessageText(q.message.chat.id,q.message.message_id,undefined,'❌ Selected operator is no longer available. Please try again.');const c=await cfg(),rr=await rate(),price=sell(o.cost??o.price??o.rate,c,rr),stock=num(o.count??o.stock??o.qty??o.quantity??o.available);if(stock<=0)return this.telegram.editMessageText(q.message.chat.id,q.message.message_id,undefined,'❌ Selected operator is out of stock. Please choose another operator.');return this.telegram.editMessageText(q.message.chat.id,q.message.message_id,undefined,`⚠️ Confirm Number\n\n🖥 Server : 3\n📦 Service: ${service}\n🌍 Country: ${country}\n📡 Operator: ${operator}\n\n💰 Price: ₹${price}\n📦 Live Stock: ${stock}\n\nYour configured profit/markup is included in this price.\n\nContinue with this operator?`,Markup.inlineKeyboard([[Markup.button.callback('✅ Continue','5confirm:'+enc(country)+':'+enc(service)+':'+enc(operator))],[Markup.button.callback('❌ Decline','5decline')]]))}
if(q&&uid&&cb.startsWith('5confirm:')){const z=cb.split(':'),country=dec(z[1]),service=dec(z[2]),operator=dec(z.slice(3).join(':'));try{await this.telegram.answerCbQuery(q.id)}catch{};return buy5(this,uid,country,service,operator)}
if(q&&uid&&cb==='5decline'){try{await this.telegram.answerCbQuery(q.id)}catch{};return this.telegram.editMessageText(q.message.chat.id,q.message.message_id,undefined,'❌ Request declined.\n\nNumber request cancelled.',Markup.inlineKeyboard([[Markup.button.callback('⬅ Countries','fsearch:5sim')]]))}}catch(e){console.log('5SIM CONFIRM:',e.message)}return prev.call(this,u,...args)};
