const mongoose=require('mongoose');const axios=require('axios');const {Telegraf,Markup}=require('telegraf');
const FB='https://5sim.net/v1';
const cache5=new Map();
const enc5=x=>encodeURIComponent(String(x));const dec5=x=>{try{return decodeURIComponent(x)}catch{return String(x)}};
async function cfg5(){try{return await mongoose.connection.db.collection('number_server_configs').findOne({server:'5sim'})}catch{return null}}
function num5(v){const n=Number(v);return Number.isFinite(n)?n:0}
function operators5(raw,service,country){const out=[];const seen=new Set();const add=(name,o)=>{if(!o||typeof o!=='object')return;const price=num5(o.cost??o.price??o.rate??o.sell_price??o.buy_price);const stock=num5(o.count??o.stock??o.qty??o.quantity??o.available);if(price<=0&&stock<=0)return;const key=String(name||o.operator||o.name||'Unknown');if(seen.has(key))return;seen.add(key);out.push({name:key,price,stock})};
const walk=(o,path=[])=>{if(!o||typeof o!=='object')return;if(Array.isArray(o)){o.forEach(x=>walk(x,path));return}for(const[k,v]of Object.entries(o)){if(!v||typeof v!=='object')continue;const np=path.concat(k);if(String(k).toLowerCase()===String(country).toLowerCase()||String(k).toLowerCase().replace(/[_-]/g,'')===String(country).toLowerCase().replace(/[_-]/g,'')){walk(v,np);continue}if(np.some(x=>String(x).toLowerCase()===String(service).toLowerCase())){if(typeof v==='object'){for(const[op,val]of Object.entries(v)){if(val&&typeof val==='object')add(op,val)}}}walk(v,np)}};walk(raw);return out}
async function raw5(country,service){const key='5c:'+country+':'+service,h=cache5.get(key);if(h&&Date.now()-h.t<5000)return h.v;const d=(await axios.get(FB+'/guest/prices',{params:{country,product:service},timeout:20000,headers:{Accept:'application/json'}})).data;cache5.set(key,{t:Date.now(),v:d});return d}
const prev5=Telegraf.prototype.handleUpdate;Telegraf.prototype.handleUpdate=async function(u,...args){try{const q=u?.callback_query,cb=q?.data||'',uid=q?.from?.id;if(q&&uid&&cb.startsWith('fbuy:5sim:')){const z=cb.split(':'),country=dec5(z[2]),service=dec5(z.slice(3).join(':'));try{await this.telegram.answerCbQuery(q.id)}catch{};let ops=[];try{const raw=await raw5(country,service);ops=operators5(raw,service,country)}catch(e){console.log('5SIM CONFIRM FETCH:',e.response?.data||e.message)}const c=await cfg5();const rr=(()=>{try{const x=Number(c?.usdtInrRate);return Number.isFinite(x)&&x>0?x:100}catch{return 100}})();const pct=num5(c?.profitPercent??c?.markup);const fixed=num5(c?.profit??c?.profitAmount);let lines=[];for(const o of ops){let p=o.price*rr;if(fixed>0)p+=fixed;if(pct>0)p*=1+pct/100;p=Math.ceil(p*100)/100;lines.push(`• ${o.name}: ₹${p} | Stock: ${o.stock}`)}if(!lines.length)lines.push('❌ Operator price/stock unavailable right now.');const text=`⚠️ Confirm 5SIM Number\n\n📦 Service: ${service}\n🌍 Country: ${country}\n\n💰 Live operator pricing:\n${lines.join('\n')}\n\nPrices/stock were fetched live from 5SIM.\n\nContinue to request a number?`;const rows=[[Markup.button.callback('✅ Continue','5confirm:'+enc5(country)+':'+enc5(service))],[Markup.button.callback('❌ Decline','5decline')]];return this.telegram.editMessageText(q.message.chat.id,q.message.message_id,undefined,text,Markup.inlineKeyboard(rows))}
if(q&&uid&&cb.startsWith('5confirm:')){const z=cb.split(':'),country=dec5(z[1]),service=dec5(z.slice(2).join(':'));try{await this.telegram.answerCbQuery(q.id)}catch{};return prev5.call(this,{...u,callback_query:{...q,data:'ns_buy_5sim_'+enc5(country)+'_'+enc5(service)}},...args)}
if(q&&uid&&cb==='5decline'){try{await this.telegram.answerCbQuery(q.id)}catch{};return this.telegram.editMessageText(q.message.chat.id,q.message.message_id,undefined,'❌ Request declined.\n\nNumber request cancelled.',Markup.inlineKeyboard([[Markup.button.callback('⬅ Countries','fsearch:5sim')]]))}}catch(e){console.log('5SIM CONFIRM:',e.message)}return prev5.call(this,u,...args)};
