const mongoose=require('mongoose');
const axios=require('axios');
const {Telegraf,Markup,Telegram}=require('telegraf');
const OWNER_ID=5087094625;
const FIVE_BASE='https://5sim.net/v1';
const FIVE_TOKEN=process.env.FIVESIM_API_KEY||process.env.FIVE_SIM_API_KEY||process.env['5SIM_API_KEY']||'';
const VAK_KEY=process.env.VAKSMS_API_KEY||'';
const VAK_BASE='https://vak-sms.com/stubs/handler_api.php';
const DEFAULT_USDT_INR=100;
const states=new Map();
const schema=new mongoose.Schema({server:{type:String,unique:true},countries:{type:Array,default:[]},services:{type:Array,default:[]},operators:{type:Array,default:[]},markup:{type:Number,default:0}},{collection:'number_server_configs'});
const Config=mongoose.models.NumberServerImportConfig||mongoose.model('NumberServerImportConfig',schema);
async function cfg(server){return Config.findOneAndUpdate({server},{server},{upsert:true,new:true,setDefaultsOnInsert:true});}
async function admin(id){if(Number(id)===OWNER_ID)return true;try{return !!(await mongoose.models.Admin?.findOne({userId:String(id)}));}catch{return false;}}
function enc(x){return encodeURIComponent(String(x));} function dec(x){try{return decodeURIComponent(x)}catch{return String(x)}}
async function fiveGuest(path){try{return (await axios.get(FIVE_BASE+path,{timeout:20000})).data}catch{return null}}
async function vak(action,params={}){try{return (await axios.get(VAK_BASE,{params:{action,api_key:VAK_KEY,...params},timeout:20000})).data}catch{return null}}
async function rate(){try{const d=await mongoose.connection.db.collection('settings').findOne({key:'usdtInrRate'});const n=Number(d?.value);return Number.isFinite(n)&&n>0?n:DEFAULT_USDT_INR}catch{return DEFAULT_USDT_INR}}
function providerPrice(block){if(!block)return null;const out=[];const walk=(v,d=0)=>{if(!v||d>5)return;if(Array.isArray(v)){v.forEach(x=>walk(x,d+1));return}if(typeof v==='object'){for(const k of ['cost','price','rate','sell_price','buy_price']){const n=Number(v[k]);if(Number.isFinite(n)&&n>0)out.push(n)}Object.values(v).forEach(x=>{if(x&&typeof x==='object')walk(x,d+1)})}};walk(block);return out.length?Math.min(...out):null}
function findBlock(data,country,service){if(!data||typeof data!=='object')return null;if(data[country]?.[service])return data[country][service];if(data[service]?.[country])return data[service][country];let found=null;const walk=(o,d=0)=>{if(found||!o||typeof o!=='object'||d>6)return;if(o[country]?.[service]){found=o[country][service];return}if(o[service]?.[country]){found=o[service][country];return}Object.values(o).forEach(x=>{if(x&&typeof x==='object')walk(x,d+1)})};walk(data);return found}
async function fiveInfo(country,service,operator){const d=await fiveGuest(`/guest/prices?country=${enc(country)}&product=${enc(service)}`);const b=d?.[country]?.[service];if(!b)return {stock:0,price:null};const vals=operator&&operator!=='any'&&b[operator]?[b[operator]]:Object.values(b);return {stock:vals.reduce((n,v)=>n+(Number(v?.count)||0),0),price:operator&&operator!=='any'&&b[operator]?Number(b[operator].cost):Math.min(...vals.map(v=>Number(v?.cost)).filter(Number.isFinite))};}
async function vakInfo(country,service){const d=await vak('getPrices',{country,service});const b=findBlock(d,country,service);let stock=0;if(b&&typeof b==='object'){const walk=v=>{if(!v||typeof v!=='object')return;if(Array.isArray(v)){v.forEach(walk);return}if('count' in v)stock+=Number(v.count)||0;Object.values(v).forEach(x=>{if(x&&typeof x==='object')walk(x)})};walk(b)}return {stock,price:providerPrice(b)};}
function calcPrice(s,info,r,markup){const manual=Number(s.price||0);if(manual>0)return Math.ceil(manual);if(info.price==null)return 0;return Math.ceil(info.price*r*(1+Number(markup||0)/100));}
async function render(bot,q,server,countryId,page=1){const c=await cfg(server),co=c.countries.find(x=>String(x.id)===String(countryId));if(!co)return;const arr=c.services.slice((page-1)*5,page*5),total=Math.max(1,Math.ceil(c.services.length/5)),r=await rate(),rows=[];for(const s of arr){let info=server==='5sim'?await fiveInfo(co.id,s.id,c.operators.find(o=>String(o.country)===String(co.id)&&String(o.service).toLowerCase()===String(s.id).toLowerCase())?.operator||'any'):await vakInfo(co.id,s.id);let p=calcPrice(s,info,r,c.markup);rows.push([Markup.button.callback(`📦 ${s.name} • ₹${p} • Stock: ${info.stock}`,`ns_buy_${server}_${enc(co.id)}_${enc(s.id)}`)])}const nav=[];if(page>1)nav.push(Markup.button.callback('⬅',`nsi_s_${server}_${enc(co.id)}_${page-1}`));if(page<total)nav.push(Markup.button.callback('➡',`nsi_s_${server}_${enc(co.id)}_${page+1}`));if(nav.length)rows.push(nav);rows.push([Markup.button.callback('⬅ Countries',`nsi_c_${server}_1`)]);return bot.telegram.editMessageText(q.message.chat.id,q.message.message_id,undefined,`📦 Select Service\n\n🌍 ${co.name}\n\nPage ${page}/${total}`,Markup.inlineKeyboard(rows));}
async function renderCountries(bot,q,server,page=1){const c=await cfg(server),arr=c.countries.slice((page-1)*5,page*5),total=Math.max(1,Math.ceil(c.countries.length/5));const rows=arr.map(x=>[Markup.button.callback(`🌍 ${x.name}`,`nsi_country_${server}_${enc(x.id)}`)]);const nav=[];if(page>1)nav.push(Markup.button.callback('⬅',`nsi_c_${server}_${page-1}`));if(page<total)nav.push(Markup.button.callback('➡',`nsi_c_${server}_${page+1}`));if(nav.length)rows.push(nav);rows.push([Markup.button.callback('⬅ Servers','ns_user_menu')]);return bot.telegram.editMessageText(q.message.chat.id,q.message.message_id,undefined,`🌍 Select Country\n\nPage ${page}/${total}`,Markup.inlineKeyboard(rows));}
async function importFive(){if(!FIVE_TOKEN)throw Error('FIVESIM_API_KEY is not configured');const c=await cfg('5sim');const oldPrice=new Map(c.services.map(s=>[String(s.id),Number(s.price||0)]));const d=await fiveGuest('/guest/countries');let countries=[];if(Array.isArray(d))countries=d;else if(d&&typeof d==='object')countries=Object.entries(d).map(([id,v])=>({id,name:v?.name||v?.title||id,code:v?.iso||v?.code||''}));if(!countries.length){const p=await fiveGuest('/guest/prices');if(p&&typeof p==='object')countries=Object.keys(p).map(id=>({id,name:id,code:''}))}const services=new Map();for(const co of countries){const p=await fiveGuest(`/guest/prices?country=${enc(co.id)}`);const block=p?.[co.id];if(block&&typeof block==='object')Object.keys(block).forEach(id=>{if(!services.has(id))services.set(id,{id,name:id,price:oldPrice.get(id)||0})})}c.countries=countries.map(x=>({id:String(x.id).toLowerCase(),name:String(x.name||x.id),code:x.code||''}));c.services=[...services.values()];await c.save();return {countries:c.countries.length,services:c.services.length};}
async function importVak(){if(!VAK_KEY)throw Error('VAKSMS_API_KEY is not configured');const c=await cfg('vak');const oldPrice=new Map(c.services.map(s=>[String(s.id),Number(s.price||0)]));let co=await vak('getCountries');if(typeof co==='string')co=null;let countries=[];if(Array.isArray(co))countries=co;else if(co&&typeof co==='object')countries=Object.entries(co).map(([id,v])=>({id,name:v?.name||v?.title||id,code:v?.code||v?.iso||''}));if(!countries.length){const d=await vak('getPrices');if(d&&typeof d==='object')countries=Object.keys(d).map(id=>({id,name:id,code:''}))}let sv=await vak('getServices');let services=[];if(Array.isArray(sv))services=sv;else if(sv&&typeof sv==='object')services=Object.entries(sv).map(([id,v])=>({id,name:v?.name||v?.title||id}));if(!services.length){const d=await vak('getPrices');const ids=new Set();const walk=o=>{if(!o||typeof o!=='object')return;Object.entries(o).forEach(([k,v])=>{if(v&&typeof v==='object'){if(!countries.some(x=>String(x.id)===k)&&k.length<40)ids.add(k);walk(v)}})};walk(d);services=[...ids].map(id=>({id,name:id}))}c.countries=countries.map(x=>({id:String(x.id),name:String(x.name||x.id),code:x.code||''}));c.services=services.map(x=>({id:String(x.id||x.service),name:String(x.name||x.title||x.id||x.service),price:oldPrice.get(String(x.id||x.service))||0}));await c.save();return {countries:c.countries.length,services:c.services.length};}
async function sync(server,bot,uid){const r=server==='5sim'?await importFive():await importVak();await bot.telegram.sendMessage(uid,`✅ Import/Sync completed\n\n🌍 Countries: ${r.countries}\n📦 Services: ${r.services}`);}
function adminMenu(server){return Markup.inlineKeyboard([[Markup.button.callback('📥 Import / Sync','nsi_import_'+server)],[Markup.button.callback('🗑 Remove All','nsi_remove_'+server)],[Markup.button.callback('💰 Set Price','nsi_price_'+server)],[Markup.button.callback('📈 Set Profit %','nsi_profit_'+server)],[Markup.button.callback('📋 View Settings',`nsi_view_${server}`)],[Markup.button.callback('⬅ Number Servers','admin_servers')]])}
try{const old=Telegram.prototype.callApi;Telegram.prototype.callApi=async function(method,payload,...args){try{if(method==='sendMessage'&&payload&&String(payload.text||'').includes('⚙️ 5SIM SETTINGS')||method==='sendMessage'&&payload&&String(payload.text||'').includes('⚙️ VAK-SMS SETTINGS')){if(payload.reply_markup){const kb=payload.reply_markup.inline_keyboard||[];if(!kb.some(r=>r.some(b=>String(b.callback_data||'').startsWith('nsi_import_')))){kb.push([{text:'📥 Import / Sync',callback_data:'nsi_import_'+(String(payload.text).includes('5SIM')?'5sim':'vak')}],[{text:'🗑 Remove All',callback_data:'nsi_remove_'+(String(payload.text).includes('5SIM')?'5sim':'vak')}],[{text:'💰 Set Price',callback_data:'nsi_price_'+(String(payload.text).includes('5SIM')?'5sim':'vak')}],[{text:'📈 Set Profit %',callback_data:'nsi_profit_'+(String(payload.text).includes('5SIM')?'5sim':'vak')}]);payload.reply_markup.inline_keyboard=kb}}}catch{}return old.call(this,method,payload,...args)}}catch{}
const previous=Telegraf.prototype.handleUpdate;Telegraf.prototype.handleUpdate=async function(update,...args){try{const q=update?.callback_query,cb=q?.data||'',uid=q?.from?.id;if(uid&&await admin(uid)){if(cb==='ns_5sim'||cb==='ns_vak'){try{await this.telegram.answerCbQuery(q.id)}catch{};return this.telegram.sendMessage(uid,`⚙️ ${cb==='ns_5sim'?'5SIM':'VAK-SMS'} SETTINGS`,adminMenu(cb==='ns_5sim'?'5sim':'vak'))}if(cb.startsWith('nsi_import_')){const s=cb.slice(11);try{await this.telegram.answerCbQuery(q.id,'⏳ Importing...')}catch{};try{return sync(s,this,uid)}catch(e){return this.telegram.sendMessage(uid,'❌ '+e.message)}}if(cb.startsWith('nsi_remove_')){const s=cb.slice(11),c=await cfg(s);c.countries=[];c.services=[];c.operators=[];await c.save();try{await this.telegram.answerCbQuery(q.id)}catch{};return this.telegram.sendMessage(uid,'✅ All imported countries & services removed.')}if(cb.startsWith('nsi_price_')||cb.startsWith('nsi_profit_')){const s=cb.split('_').pop(),type=cb.startsWith('nsi_price_')?'price':'profit';states.set(String(uid),{server:s,type});try{await this.telegram.answerCbQuery(q.id)}catch{};return this.telegram.sendMessage(uid,type==='price'?'💰 Send default service price in ₹. Example: 50':'📈 Send default profit percentage. Example: 20')}}if(uid&&update.message?.chat?.type==='private'&&update.message?.text&&!update.message.text.startsWith('/')&&states.has(String(uid))&&await admin(uid)){const st=states.get(String(uid));states.delete(String(uid));const c=await cfg(st.server);const n=Number(update.message.text.trim());if(!Number.isFinite(n)||n<0)return this.telegram.sendMessage(uid,'❌ Invalid number');if(st.type==='price')c.services.forEach(x=>x.price=n);else c.markup=n;await c.save();return this.telegram.sendMessage(uid,`✅ ${st.type==='price'?'Price':'Profit %'} saved: ${n}${st.type==='profit'?'%':'₹'}`)}if(q&&uid){if(cb.startsWith('nsi_country_')){try{await this.telegram.answerCbQuery(q.id)}catch{};return render(this,q,cb.split('_')[2],dec(cb.split('_')[3]),1)}if(cb.startsWith('nsi_c_')){const p=cb.split('_');try{await this.telegram.answerCbQuery(q.id)}catch{};return renderCountries(this,q,p[2],Number(p[3])||1)}if(cb.startsWith('nsi_s_')){const p=cb.split('_');try{await this.telegram.answerCbQuery(q.id)}catch{};return render(this,q,p[2],dec(p[3]),Number(p[4])||1)}}}catch(e){console.log('IMPORT PRICING BOOT:',e.message)}return previous.call(this,update,...args)};
