const mongoose=require('mongoose');
const axios=require('axios');
const {Telegraf,Markup}=require('telegraf');
const OWNER_ID=5087094625;
const FIVE_BASE='https://5sim.net/v1';
const FIVE_TOKEN=process.env.FIVESIM_API_KEY||process.env.FIVE_SIM_API_KEY||process.env['5SIM_API_KEY']||'';
const VAK_KEY=process.env.VAKSMS_API_KEY||'';
const VAK_BASE='https://vak-sms.com/stubs/handler_api.php';
const DEFAULT_USDT_INR=100;
const states=new Map();
const schema=new mongoose.Schema({server:{type:String,unique:true},countries:{type:Array,default:[]},services:{type:Array,default:[]},operators:{type:Array,default:[]},markup:{type:Number,default:0}},{collection:'number_server_configs'});
const Config=mongoose.models.NumberServerImportConfig||mongoose.model('NumberServerImportConfig',schema);
async function cfg(server){return Config.findOneAndUpdate({server},{server},{upsert:true,new:true,setDefaultsOnInsert:true});}
async function admin(id){if(Number(id)===OWNER_ID)return true;try{return !!(await mongoose.models.Admin?.findOne({userId:String(id)}));}catch{return false;}}
function enc(x){return encodeURIComponent(String(x));}function dec(x){try{return decodeURIComponent(x)}catch{return String(x)}}
async function fiveGuest(path){try{return(await axios.get(FIVE_BASE+path,{timeout:30000,headers:{Accept:'application/json'}})).data}catch{return null}}
async function vak(action,params={}){if(!VAK_KEY)throw Error('VAKSMS_API_KEY is not configured');const r=await axios.get(VAK_BASE,{params:{action,api_key:VAK_KEY,...params},timeout:30000,headers:{Accept:'application/json'}});return r.data}
function validObj(x){return x&&typeof x==='object'&&!Array.isArray(x)}
function deepMerge(a,b){if(!validObj(a))a={};if(!validObj(b))return a;for(const [k,v] of Object.entries(b)){if(validObj(v))a[k]=deepMerge(validObj(a[k])?a[k]:{},v);else a[k]=v}return a}
function leaf(v){return validObj(v)&&['cost','price','rate','count','stock','qty','quantity','available','sell_price','buy_price'].some(k=>v[k]!=null)}
function pretty5Name(id){const s=String(id||'').trim();const known={tg:'Telegram',wa:'WhatsApp',go:'Google',ig:'Instagram',fb:'Facebook',tw:'Twitter',vk:'VKontakte',vi:'Viber',wb:'WeChat',ds:'Discord',am:'Amazon',av:'Avito',ok:'Odnoklassniki',ub:'Uber',oi:'OpenAI',nf:'Netflix'};if(known[s.toLowerCase()])return known[s.toLowerCase()];return s.replace(/[_-]+/g,' ').replace(/\b\w/g,m=>m.toUpperCase())}
function normalizeCountry(id,v,names){const x=validObj(v)?v:{};return{id:String(id),name:String(names?.get(String(id))||x.name||x.title||x.text_en||x.eng||x.rus||id),code:String(x.iso||x.iso2||x.code||'')}}
function normalizeService(id,v,names,server){const x=validObj(v)?v:{};const code=String(id);return{id:code,name:String(names?.get(code)||x.name||x.title||x.text_en||x.eng||x.rus||(server==='5sim'?pretty5Name(code):code)),price:0}}
function extractTree(tree){const countries=new Map(),services=new Map();const walk=(o,path=[])=>{if(!validObj(o)||path.length>8)return;for(const [k,v] of Object.entries(o)){if(!validObj(v))continue;if(leaf(v)){if(path.length){const parent=path[path.length-1];const grand=path[path.length-2];if(grand!=null){countries.set(String(grand),true);services.set(String(parent),true)}else{services.set(String(parent),true)}}continue;}if(path.length===0){/* top-level country or service; resolved by child shape below */}walk(v,path.concat(k));}};walk(tree);
// Determine orientation more reliably from the first non-empty branch.
for(const [k,v] of Object.entries(tree||{})){if(!validObj(v))continue;const keys=Object.entries(v).filter(([,x])=>validObj(x));if(!keys.length)continue;const leafChildren=keys.some(([,x])=>leaf(x));if(leafChildren){countries.set(String(k),true);for(const [sk,sv] of keys)if(validObj(sv))services.set(String(sk),true);continue;}for(const [sk,sv] of keys){if(!validObj(sv))continue;const nested=Object.entries(sv).filter(([,x])=>validObj(x));if(nested.some(([,x])=>leaf(x))){services.set(String(k),true);for(const [ck] of nested)countries.set(String(ck),true)}}}
return{countries:[...countries.keys()],services:[...services.keys()]}}
function priceCountries(tree){const out=new Set();const walk=(o,depth=0)=>{if(!validObj(o)||depth>7)return;for(const [k,v] of Object.entries(o)){if(!validObj(v))continue;const child=Object.entries(v).filter(([,x])=>validObj(x));if(child.some(([,x])=>leaf(x)))out.add(String(k));walk(v,depth+1)}};walk(tree);return [...out]}
async function rate(){try{const d=await mongoose.connection.db.collection('settings').findOne({key:'usdtInrRate'});const n=Number(d?.value);return Number.isFinite(n)&&n>0?n:DEFAULT_USDT_INR}catch{return DEFAULT_USDT_INR}}
function providerPrice(block){if(!block)return null;const out=[];const walk=(v,d=0)=>{if(!v||d>6)return;if(Array.isArray(v)){v.forEach(x=>walk(x,d+1));return}if(validObj(v)){for(const k of ['cost','price','rate','sell_price','buy_price']){const n=Number(v[k]);if(Number.isFinite(n)&&n>0)out.push(n)}Object.values(v).forEach(x=>walk(x,d+1))}};walk(block);return out.length?Math.min(...out):null}
function findBlock(data,country,service){if(!validObj(data))return null;if(data[country]?.[service])return data[country][service];if(data[service]?.[country])return data[service][country];let found=null;const walk=(o,d=0)=>{if(found||!validObj(o)||d>7)return;if(o[country]?.[service]){found=o[country][service];return}if(o[service]?.[country]){found=o[service][country];return}Object.values(o).forEach(x=>walk(x,d+1))};walk(data);return found}
async function importFive(){if(!FIVE_TOKEN)throw Error('FIVESIM_API_KEY is not configured');const c=await cfg('5sim'),old=new Map(c.services.map(s=>[String(s.id),Number(s.price||0)]));const d=await fiveGuest('/guest/countries');if(!validObj(d))throw Error('5SIM countries could not be loaded');const countries=Object.entries(d).map(([id,v])=>normalizeCountry(id,v));const services=new Map();for(const co of countries){const p=await fiveGuest(`/guest/prices?country=${enc(co.id)}`);const b=p?.[co.id];if(validObj(b))for(const id of Object.keys(b))if(!services.has(id))services.set(id,{id,name:pretty5Name(id),price:old.get(String(id))||0})}c.countries=countries;c.services=[...services.values()];await c.save();return{countries:c.countries.length,services:c.services.length}}
async function importVak(){
 if(!VAK_KEY)throw Error('VAKSMS_API_KEY is not configured');
 const c=await cfg('vak');
 const oldPrice=new Map(c.services.map(s=>[String(s.id),Number(s.price||0)]));
 const countryNames=new Map(),serviceNames=new Map();
 // Names are optional; the price tree is the source of truth for what is actually available.
 try{const d=await vak('getCountries');if(Array.isArray(d))d.forEach((x,i)=>{if(validObj(x))countryNames.set(String(x.id??x.code??i),String(x.name||x.title||x.text_en||x.eng||x.rus||x.id||i));else countryNames.set(String(i),String(x))});else if(validObj(d))for(const [id,v] of Object.entries(d))countryNames.set(String(id),String(validObj(v)?(v.name||v.title||v.text_en||v.eng||v.rus||id):v))}catch(e){console.log('VAK IMPORT countries names:',e.response?.data||e.message)}
 try{const d=await vak('getServices');if(Array.isArray(d))d.forEach((x,i)=>{if(validObj(x))serviceNames.set(String(x.id??x.code??i),String(x.name||x.title||x.text_en||x.eng||x.rus||x.id||i));else serviceNames.set(String(i),String(x))});else if(validObj(d?.services))for(const x of d.services)if(validObj(x))serviceNames.set(String(x.id??x.code),String(x.name||x.title||x.text_en||x.eng||x.rus||x.id||x.code));else if(validObj(d))for(const [id,v] of Object.entries(d))serviceNames.set(String(id),String(validObj(v)?(v.name||v.title||v.text_en||v.eng||v.rus||id):v))}catch(e){console.log('VAK IMPORT services names:',e.response?.data||e.message)}
 let merged={};
 let operators=[];
 try{const od=await vak('getOperators');if(Array.isArray(od))operators=od.map(x=>validObj(x)?String(x.id??x.code??x.operator??x.name):String(x)).filter(Boolean);else if(validObj(od))operators=Object.entries(od).map(([k,v])=>validObj(v)?String(v.id??v.code??v.operator??k):String(v)).filter(Boolean)}catch(e){console.log('VAK IMPORT operators:',e.response?.data||e.message)}
 operators=[...new Set(operators)];
 if(operators.length){for(const op of operators){try{const d=await vak('getPrices',{operator:op});if(validObj(d))merged=deepMerge(merged,d)}catch(e){console.log('VAK IMPORT price',op,e.response?.data||e.message)}}}
 if(!Object.keys(merged).length){try{const d=await vak('getPrices');if(validObj(d))merged=d}catch(e){console.log('VAK IMPORT price fallback:',e.response?.data||e.message)}}
 if(!validObj(merged)||!Object.keys(merged).length)throw Error('VAK-SMS returned no price/catalog data. Check VAK API key.');
 const parsed=extractTree(merged);let countryIds=parsed.countries,serviceIds=parsed.services;
 // Fallback orientation parser for VAK price trees.
 if(!countryIds.length||!serviceIds.length){const top=Object.entries(merged);for(const [k,v] of top){if(!validObj(v))continue;const children=Object.entries(v).filter(([,x])=>validObj(x));if(children.some(([,x])=>leaf(x))){countryIds.push(k);children.forEach(([sk])=>serviceIds.push(sk))}else{for(const [sk,sv] of children){if(validObj(sv)&&Object.entries(sv).some(([,x])=>leaf(x))){serviceIds.push(k);countryIds.push(sk)}}}}}
 countryIds=[...new Set(countryIds.map(String))];serviceIds=[...new Set(serviceIds.map(String))];
 if(!countryIds.length||!serviceIds.length)throw Error('VAK-SMS price data format could not be parsed into countries/services.');
 c.countries=countryIds.map(id=>normalizeCountry(id,{},countryNames));
 c.services=serviceIds.map(id=>{const x=normalizeService(id,{},serviceNames,'vak');x.price=oldPrice.get(id)||0;return x});
 c.operators=operators.map(operator=>({operator}));
 await c.save();
 return{countries:c.countries.length,services:c.services.length,operators:c.operators.length};
}
async function sync(server,bot,uid){const r=server==='5sim'?await importFive():await importVak();await bot.telegram.sendMessage(uid,`✅ Import/Sync completed\n\n🌍 Countries: ${r.countries}\n📦 Services: ${r.services}${r.operators!=null?`\n📡 Operators: ${r.operators}`:''}`)}
function adminMenu(server){return Markup.inlineKeyboard([[Markup.button.callback('📥 Import / Sync','nsi_import_'+server)],[Markup.button.callback('🗑 Remove All','nsi_remove_'+server)],[Markup.button.callback('💰 Set Price','nsi_price_'+server)],[Markup.button.callback('📈 Set Profit %','nsi_profit_'+server)],[Markup.button.callback('📋 View Settings',`nsi_view_${server}`)],[Markup.button.callback('🔎 Search Countries',`nss_${server}_countries`)],[Markup.button.callback('🔎 Search Services',`nss_${server}_services`)],[Markup.button.callback('⬅ Number Servers','admin_servers')]])}
const previous=Telegraf.prototype.handleUpdate;
Telegraf.prototype.handleUpdate=async function(update,...args){try{const q=update?.callback_query,cb=q?.data||'',uid=q?.from?.id;if(uid&&await admin(uid)){if(cb==='ns_5sim'||cb==='ns_vak'){try{await this.telegram.answerCbQuery(q.id)}catch{};return this.telegram.sendMessage(uid,`⚙️ ${cb==='ns_5sim'?'5SIM':'VAK-SMS'} SETTINGS`,adminMenu(cb==='ns_5sim'?'5sim':'vak'))}if(cb.startsWith('nsi_import_')){const s=cb.slice(11);try{await this.telegram.answerCbQuery(q.id,'⏳ Importing...')}catch{};try{return await sync(s,this,uid)}catch(e){console.log('IMPORT SYNC ERROR',s,e.response?.data||e.message);return this.telegram.sendMessage(uid,'❌ '+e.message)}}if(cb.startsWith('nsi_remove_')){const s=cb.slice(11),c=await cfg(s);c.countries=[];c.services=[];c.operators=[];await c.save();try{await this.telegram.answerCbQuery(q.id)}catch{};return this.telegram.sendMessage(uid,'✅ All imported countries & services removed.')}if(cb.startsWith('nsi_price_')||cb.startsWith('nsi_profit_')){const s=cb.split('_').pop(),type=cb.startsWith('nsi_price_')?'price':'profit';states.set(String(uid),{server:s,type});try{await this.telegram.answerCbQuery(q.id)}catch{};return this.telegram.sendMessage(uid,type==='price'?'💰 Send default service price in ₹. Example: 50':'📈 Send default profit percentage. Example: 20')}if(update.message?.chat?.type==='private'&&update.message?.text&&!update.message.text.startsWith('/')&&states.has(String(uid))){const st=states.get(String(uid));states.delete(String(uid));const c=await cfg(st.server);const n=Number(update.message.text.trim());if(!Number.isFinite(n)||n<0)return this.telegram.sendMessage(uid,'❌ Invalid number');if(st.type==='price')c.services.forEach(x=>x.price=n);else c.markup=n;await c.save();return this.telegram.sendMessage(uid,`✅ ${st.type==='price'?'Price':'Profit %'} saved: ${n}${st.type==='profit'?'%':'₹'}`)}}}catch(e){console.log('IMPORT PRICING BOOT:',e.message)}return previous.call(this,update,...args)};
