const mongoose = require('mongoose');
const { Telegraf, Markup } = require('telegraf');

const OWNER_ID = 5087094625;
const states = new Map();
const cfgSchema = new mongoose.Schema({server:{type:String,unique:true},countries:{type:Array,default:[]},services:{type:Array,default:[]},operators:{type:Array,default:[]},markup:{type:Number,default:0}},{collection:'number_server_configs'});
const Config = mongoose.models.NumberServerListsConfig || mongoose.model('NumberServerListsConfig',cfgSchema);
async function admin(id){if(Number(id)===OWNER_ID)return true;try{return !!(await mongoose.models.Admin?.findOne({userId:String(id)}));}catch{return false;}}
async function cfg(server){return Config.findOneAndUpdate({server},{server},{upsert:true,new:true,setDefaultsOnInsert:true});}
function enc(s){return encodeURIComponent(String(s));}
function dec(s){try{return decodeURIComponent(s)}catch{return String(s)}}
function filtered(arr,q){if(!q)return arr;const s=q.toLowerCase();return arr.filter(x=>String(x.name||'').toLowerCase().includes(s)||String(x.id||'').toLowerCase().includes(s)||String(x.code||'').toLowerCase().includes(s));}
async function settingsMenu(bot,uid,server){const c=await cfg(server),title=server==='vak'?'VAK-SMS':'5SIM';const rows=[[Markup.button.callback('📥 Import / Sync All',`nsi_import_${server}`)],[Markup.button.callback('🌍 Add Country',`vfix_${server}_add_country`),Markup.button.callback('🗑 Remove Country',`vfix_${server}_del_country`)],[Markup.button.callback('📦 Add Service',`vfix_${server}_add_service`),Markup.button.callback('🗑 Remove Service',`vfix_${server}_del_service`)],[Markup.button.callback('📋 Countries List',`nsl_${server}_countries_1`),Markup.button.callback('📋 Services List',`nsl_${server}_services_1`)],[Markup.button.callback('🔎 Search Countries',`nss_${server}_countries`),Markup.button.callback('🔎 Search Services',`nss_${server}_services`)]];if(server==='5sim')rows.push([Markup.button.callback('📡 Operators List','nsl_5sim_operators_1')]);rows.push([Markup.button.callback('⬅ Number Servers','admin_servers')]);return bot.telegram.sendMessage(uid,`⚙️ ${title} SETTINGS\n\nCountries: ${c.countries.length}\nServices: ${c.services.length}${server==='5sim'?`\nOperators: ${c.operators.length}`:''}`,Markup.inlineKeyboard(rows));}
async function listPage(bot,uid,server,type,p=1,q=''){const c=await cfg(server);const raw=type==='countries'?c.countries:type==='services'?c.services:c.operators;const arr=type==='operators'?raw:filtered(raw,q);const total=Math.max(1,Math.ceil(arr.length/10));p=Math.min(Math.max(1,p),total);const items=arr.slice((p-1)*10,p*10);let text=`📋 ${server.toUpperCase()} ${type.toUpperCase()}\n`;if(q)text+=`🔎 Search: ${q}\n`;text+='\n';if(!items.length)text+='No matching items found.\n';else if(type==='countries')items.forEach((x,i)=>text+=`${(p-1)*10+i+1}. ${x.name}\n   ID: ${x.id}${x.code?`\n   Code: ${x.code}`:''}\n\n`);else if(type==='services')items.forEach((x,i)=>text+=`${(p-1)*10+i+1}. ${x.name}\n   API: ${x.id}${x.price!=null?`\n   Price: ₹${x.price}`:''}\n\n`);else items.forEach((x,i)=>text+=`${(p-1)*10+i+1}. ${x.country} | ${x.service} | ${x.operator}\n\n`);const rows=[],nav=[];if(p>1)nav.push(Markup.button.callback('⬅ Previous',`nsl_${server}_${type}_${p-1}${q?`_${enc(q)}`:''}`));if(p<total)nav.push(Markup.button.callback('Next ➡',`nsl_${server}_${type}_${p+1}${q?`_${enc(q)}`:''}`));if(nav.length)rows.push(nav);if(type!=='operators')rows.push([Markup.button.callback('🔎 New Search',`nss_${server}_${type}`)]);rows.push([Markup.button.callback('⚙️ Settings',`ns_${server}`)]);return bot.telegram.sendMessage(uid,text+`Page ${p}/${total}`,Markup.inlineKeyboard(rows));}
const original=Telegraf.prototype.handleUpdate;
Telegraf.prototype.handleUpdate=async function(update,...args){try{const from=update?.message?.from||update?.callback_query?.from,uid=from?.id,cb=update?.callback_query?.data||'';if(uid&&await admin(uid)){if(cb==='admin_servers'){try{await this.telegram.answerCbQuery(update.callback_query.id)}catch{}return this.telegram.sendMessage(uid,'🖥 NUMBER SERVERS ADMIN\n\nChoose server:',Markup.inlineKeyboard([[Markup.button.callback('🟢 5SIM Settings','ns_5sim')],[Markup.button.callback('🔵 VAK-SMS Settings','ns_vak')],[Markup.button.callback('⬅ Admin Panel','admin_panel')]]));}if(cb==='ns_5sim'||cb==='ns_vak'){try{await this.telegram.answerCbQuery(update.callback_query.id)}catch{}return settingsMenu(this,uid,cb==='ns_vak'?'vak':'5sim');}let m=cb.match(/^nss_(5sim|vak)_(countries|services)$/);if(m){states.set(String(uid),{server:m[1],type:m[2]});try{await this.telegram.answerCbQuery(update.callback_query.id)}catch{}return this.telegram.sendMessage(uid,`🔎 ${m[2]==='countries'?'Country':'Service'} Search\n\nSend name, ID/API${m[2]==='countries'?' or code':''} to search:`);}m=cb.match(/^nsl_(5sim|vak)_(countries|services|operators)_(\d+)(?:_(.*))?$/);if(m){try{await this.telegram.answerCbQuery(update.callback_query.id)}catch{}return listPage(this,uid,m[1],m[2],Number(m[3])||1,m[4]?dec(m[4]):'');}if(update.message?.chat?.type==='private'&&update.message.text&&!update.message.text.startsWith('/')&&states.has(String(uid))){const st=states.get(String(uid));states.delete(String(uid));return listPage(this,uid,st.server,st.type,1,update.message.text.trim());}}}catch(e){console.log('NUMBER SERVER LISTS ERROR:',e.message);}return original.call(this,update,...args)};
