const express=require('express');
const crypto=require('crypto');
const axios=require('axios');
const mongoose=require('mongoose');
const {Telegraf,Markup}=require('telegraf');
const API='https://api.omniupi.in/api';
const TOKEN=process.env.OMNIUPI_API_TOKEN||process.env.OMNIUPI_TOKEN||'';
const SECRET=process.env.OMNIUPI_INSTANCE_SECRET||process.env.OMNIUPI_SECRET||'';
const WEBHOOK_PATH='/api/omniupi/webhook';
const input=new Map();
const Payment=mongoose.models.StrictPaymentFix||mongoose.model('StrictPaymentFix',new mongoose.Schema({paymentId:{type:String,unique:true},userId:String,amount:Number,credits:Number,method:{type:String,default:'OMNIUPI'},paymentNote:String,utr:{type:String,default:null},status:{type:String,default:'PENDING'},screenshotFileId:{type:String,default:null},adminId:{type:String,default:null},rejectReason:{type:String,default:null},createdAt:{type:Date,default:Date.now},expiresAt:Date},{collection:'payments'}));
const User=mongoose.models.User;
const Setting=mongoose.models.OmniUPISetting||mongoose.model('OmniUPISetting',new mongoose.Schema({key:String,value:mongoose.Schema.Types.Mixed},{collection:'settings'}));
const DepositLog=mongoose.models.OmniUPIDepositLog||mongoose.model('OmniUPIDepositLog',new mongoose.Schema({paymentId:{type:String,unique:true},createdAt:{type:Date,default:Date.now}},{collection:'purchase_deposit_logs'}));
let rate=5,depositChannel='';let botRef=null;
async function settings(){try{const[r,ch]=await Promise.all([Setting.findOne({key:'pricePerCredit'}),Setting.findOne({key:'depositLogChannel'})]);if(r)rate=Number(r.value)||5;if(ch)depositChannel=String(ch.value||'').trim()}catch{}}
settings();
function oid(){return'NEXO-OMNI-'+Date.now().toString(36).toUpperCase()+'-'+Math.floor(Math.random()*900+100)}
function sign(body){return crypto.createHmac('sha256',SECRET).update(body).digest('hex')}
async function createOrder(userId,amount){if(!TOKEN)throw Error('OmniUPI API token is not configured');const u=User?await User.findOne({userId:String(userId)}):null;const mobile=String(u?.mobile||u?.phone||u?.phoneNumber||u?.mobileNumber||'9999999999').replace(/\D/g,'').slice(-10)||'9999999999';const paymentId=oid(),credits=amount/rate;const r=await axios.post(API+'/create-order',{customer_mobile:mobile,user_token:TOKEN,amount:Number(amount).toFixed(2),order_id:paymentId,remark1:'Telegram Credit Deposit',remark2:String(userId)},{timeout:30000,headers:{'Content-Type':'application/x-www-form-urlencoded'}});const d=r.data||{},z=d.result||d,url=z.payment_url||z.paymentUrl||z.url;if(d.status!==true&&String(d.status).toLowerCase()!=='true')throw Error(d.message||'OmniUPI order creation failed');if(!url)throw Error('OmniUPI did not return payment_url');await Payment.create({paymentId,userId:String(userId),amount:Number(amount),credits:Number(credits),method:'OMNIUPI',paymentNote:String(z.orderId||paymentId),status:'PENDING',expiresAt:new Date(Date.now()+30*60*1000)});return{paymentId,credits,url}}
async function sendDepositLog(payment,txn){if(!depositChannel||!botRef)return;try{if(await DepositLog.findOne({paymentId:payment.paymentId}))return;await botRef.telegram.sendMessage(depositChannel,`🚀 New Deposit Success\n\nAmount: ₹${Number(payment.amount||0).toFixed(2).replace(/\.00$/,'')}\nPayment Method: OmniUPI (Automatic)\n💎 Credits Added: ${Number(payment.credits||0)}\n🆔 Order ID: ${payment.paymentId}\n${txn?'🔢 UTR: '+txn+'\n':''}\n\nThanks For Deposit`);await DepositLog.create({paymentId:payment.paymentId})}catch(e){console.log('OMNIUPI DEPOSIT LOG ERROR:',e.message)}}
async function credit(payment,txn){if(!payment||!User)return false;const locked=await Payment.findOneAndUpdate({paymentId:payment.paymentId,status:'PENDING'},{$set:{status:'PROCESSING',utr:String(txn||payment.utr||'')}},{new:true});if(!locked)return false;const user=await User.findOne({userId:String(payment.userId)});if(!user){await Payment.updateOne({paymentId:payment.paymentId},{$set:{status:'PENDING'}});return false}user.credits=Number(user.credits||0)+Number(payment.credits||0);await user.save();await Payment.updateOne({paymentId:payment.paymentId},{$set:{status:'APPROVED',utr:String(txn||payment.utr||'')}});await sendDepositLog(locked,txn);try{await botRef?.telegram.sendMessage(String(payment.userId),`✅ PAYMENT SUCCESSFUL\n\n💰 Paid: ₹${Number(payment.amount).toFixed(2)}\n💎 Credits Added: ${Number(payment.credits)}\n🆔 Order ID: ${payment.paymentId}\n${txn?'🔢 UTR: '+txn+'\n':''}\n💳 Your balance has been updated automatically.`)}catch{}return true}
async function status(orderId){if(!TOKEN)throw Error('OmniUPI API token is not configured');return(await axios.post(API+'/check-order-status',{user_token:TOKEN,order_id:orderId},{timeout:20000,headers:{'Content-Type':'application/x-www-form-urlencoded'}})).data||{}}
async function poll(){try{if(!TOKEN||!botRef||!mongoose.connection?.readyState)return;const ps=await Payment.find({method:'OMNIUPI',status:'PENDING',expiresAt:{$gt:new Date()}}).limit(20);for(const p of ps)try{const d=await status(p.paymentId),z=d.result||d;if(String(z.txnStatus||z.status||'').toUpperCase()==='SUCCESS')await credit(p,z.utr||z.transactionId||'')}catch(e){console.log('OMNIUPI POLL:',e.response?.data||e.message)}}catch(e){console.log('OMNIUPI POLL ERROR:',e.message)}}
// Keep normal JSON parsing and capture raw bytes for all requests.
const oldJson=express.json;express.json=function(opts={}){return oldJson({...opts,verify:(req,res,buf)=>{req.rawBody=Buffer.from(buf)}})};
// Webhook is handled here before normal routes; raw body is captured by express.json for signature verification.
const oldUse=express.application.use;let injected=false;express.application.use=function(...args){if(!injected){injected=true;oldUse.call(this,async(req,res,next)=>{if(req.method!=='POST'||req.path!==WEBHOOK_PATH)return next();try{const raw=req.rawBody||Buffer.from(JSON.stringify(req.body||{}));const got=String(req.headers['x-webhook-signature']||'');const expected=sign(raw);if(!SECRET||!got||got.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(got))){res.status(401).send('INVALID SIGNATURE');return}const body=req.body||JSON.parse(raw.toString('utf8'));if(String(req.headers['x-webhook-event']||'')!=='payment.success'||String(body.status||'').toUpperCase()!=='SUCCESS'){res.status(200).send('IGNORED');return}const id=String(body.order_id||'');if(!id){res.status(400).send('MISSING ORDER');return}const p=await Payment.findOne({paymentId:id,method:'OMNIUPI'});if(p)await credit(p,body.utr||'');res.status(200).send('SUCCESS')}catch(e){console.log('OMNIUPI WEBHOOK ERROR:',e.stack||e.message);res.status(500).send('ERROR')}})}return oldUse.apply(this,args)};
const prev=Telegraf.prototype.handleUpdate;Telegraf.prototype.handleUpdate=async function(update,...args){botRef=this;try{const uid=String(update?.callback_query?.from?.id||update?.message?.from?.id||'');const cb=update?.callback_query?.data||'';if(uid&&cb==='manual_payment'){await settings();input.set(uid,'amount');try{await this.telegram.answerCbQuery(update.callback_query.id)}catch{}return this.telegram.sendMessage(uid,`💳 ADD BALANCE\n\nEnter amount in INR.\n\n💰 Rate: ₹${rate} = 1 credit`,Markup.inlineKeyboard([[Markup.button.callback('❌ Cancel','buy')]]))}if(uid&&update.message?.chat?.type==='private'&&input.get(uid)==='amount'&&update.message.text&&!update.message.text.startsWith('/')){input.delete(uid);const amount=Number(String(update.message.text).trim());if(!Number.isFinite(amount)||amount<=0)return this.telegram.sendMessage(uid,'❌ Enter a valid amount.');if(!Number.isInteger(amount/rate))return this.telegram.sendMessage(uid,`❌ Amount must be a multiple of ₹${rate}.`);try{const o=await createOrder(uid,amount);return this.telegram.sendMessage(uid,`💳 PAYMENT CREATED\n\n💰 Amount: ₹${amount.toFixed(2)}\n💎 Credits: ${o.credits}\n🆔 Order ID: ${o.paymentId}\n\n👇 Pay using the button below.\n\n✅ After successful payment, balance will be added automatically.`,Markup.inlineKeyboard([[Markup.button.url('💳 Pay Now',o.url)],[Markup.button.callback('🔄 Check Payment','omni_check_'+o.paymentId)],[Markup.button.callback('❌ Cancel','omni_cancel_'+o.paymentId)]]))}catch(e){console.log('OMNIUPI CREATE ERROR:',e.response?.data||e.message);return this.telegram.sendMessage(uid,'❌ Payment gateway error.\n\n'+(e.response?.data?.message||e.message))}}if(uid&&cb.startsWith('omni_check_')){const id=cb.slice(11);try{await this.telegram.answerCbQuery(update.callback_query.id,'Checking...')}catch{}const p=await Payment.findOne({paymentId:id,userId:uid,method:'OMNIUPI'});if(!p)return this.telegram.sendMessage(uid,'❌ Payment not found.');const d=await status(id),z=d.result||d;if(String(z.txnStatus||z.status||'').toUpperCase()==='SUCCESS'){await credit(p,z.utr||'');return this.telegram.sendMessage(uid,'✅ Payment verified. Balance update is being processed.')}return this.telegram.sendMessage(uid,`⏳ Payment status: ${z.txnStatus||z.status||'PENDING'}\n\nPay first, then check again.`)}if(uid&&cb.startsWith('omni_cancel_')){const id=cb.slice(12),p=await Payment.findOne({paymentId:id,userId:uid,method:'OMNIUPI',status:'PENDING'});if(p){p.status='CANCELLED';await p.save()}try{await this.telegram.answerCbQuery(update.callback_query.id,'Cancelled')}catch{}return this.telegram.sendMessage(uid,'❌ Payment cancelled.')}}catch(e){console.log('OMNIUPI UPDATE ERROR:',e.stack||e.message)}return prev.call(this,update,...args)};
setInterval(poll,30000);
