const mongoose=require('mongoose');const axios=require('axios');const {Telegraf,Markup}=require('telegraf');
const FB='https://5sim.net/v1',VB='https://vak-sms.com/stubs/handler_api.php',TB='https://api.temporasms.com/stubs/handler_api.php',VK=process.env.VAKSMS_API_KEY||'',TK=process.env.TEMPORASMS_API_KEY||process.env.TEMPO_API_KEY||process.env.TEMPO_SMS_API_KEY||'';
const state=new Map(),cache=new Map();const enc=x=>encodeURIComponent(String(x)),dec=x=>{try{return decodeURIComponent(x)}catch{return String(x)}};
async function cfg(s){try{return await mongoose.connection.db.collection('number_server_configs').findOne({server:s})}catch{return null}}
async function rate(){try{const x=await mongoose.connection.db.collection('settings').findOne({key:'usdtInrRate'}),n=Number(x?.value);return Number.isFinite(n)&&n>0?n:100}catch{return 100}}
async function api(s,a,p={}){if(s==='5sim')return(await axios.get(FB+'/guest/prices',{params:p,timeout:15000})).data;if(s==='vak')return(await axios.get(VB,{params:{action:a,api_key:VK,...p},timeout:15000})).data;if(!TK)throw Error('TemporaSMS API key is not configured');return(await axios.get(TB,{params:{action:a,api_key:TK,...p},timeout:15000})).data}
const norm=x=>String(x||'').trim().toLowerCase().replace(/[^a-z0-9]/g,'');
function importedServices(c){return(c?.services||[]).map(x=>({id:String(x.id??x.code??x.service??''),name:String(x.name||x.title||x.serviceName||x.id||x.code||'')})).filter(x=>x.id&&x.name)}
function importedCountries(c){return new Map((c?.countries||[]).map(x=>[String(x.id),String(x.name||x.id)]))}
async function liveServices(s){const c=await cfg(s),k='svc:'+s,h=cache.get(k);if(h&&Date.now()-h.t<15000)return h.v;const a=importedServices(c);cache.set(k,{t:Date.now(),v:a});return a}
function block(v){let p=0,stock=0;const w=o=>{if(!o)return;if(Array.isArray(o))return o.forEach(w);if(typeof o!=='object')return;for(const k of ['cost','price','rate','sell_price','buy_price','Price']){const n=Number(o[k]);if(Number.isFinite(n)&&n>0)p=p?Math.min(p,n):n}for(const k of ['count','stock','qty','quantity','available','Qty']){const n=Number(o[k]);if(Number.isFinite(n)&&n>=0)stock+=n}for(const[k,x]of Object.entries(o))if(!['cost','price','rate','sell_price','buy_price','Price','count','stock','qty','quantity','available','Qty'].includes(k)&&x&&typeof x==='object')w(x)};w(v);return{p,stock}}
function countries(d,service){const out=[],add=(id,v)=>{const b=block(v);if(b.p>0||b.stock>0)out.push({id:String(id),...b})};if(d?.[service]&&typeof d[service]==='object'){for(const[k,v]of Object.entries(d[service]))add(k,v);return out}const w=(o,n=0)=>{if(!o||typeof o!=='object'||n>8)return;if(o[service]&&typeof o[service]==='object'){for(const[k,v]of Object.entries(o[service]))add(k,v);return}for(const v of Object.values(o))if(v&&typeof v==='object')w(v,n+1)};w(d);return out}
async function liveCountries(s,svc){const c=await cfg(s),allowed=importedCountries(c),key='ct:'+s+':'+svc.id,h=cache.get(key);if(h&&Date.now()-h.t<8000)return h.v;let d=null;try{d=s==='5sim'?await api(s,'getPrices',{product:svc.id}):await api(s,'getPrices',{service:svc.id})}catch(e){console.log('LIVE COUNTRY',s,svc.id,e.message)}let a=countries(d,svc.id);a=a.filter(x=>allowed.has(String(x.id))).map(x=>({...x,name:allowed.get(String(x.id))}));cache.set(key,{t:Date.now(),v:a});return a}
async function findImportedService(s,sel){const a=await liveServices(s);return a.find(x=>String(x.id).toLowerCase()===String(sel.id).toLowerCase())||a.find(x=>norm(x.name)===norm(sel.name))}
function sell(p,c){let x=Number(p||0),f=Number(c?.profit||c?.profitAmount||0),q=Number(c?.profitPercent||c?.markup||0);if(f>0)x+=f;if(q>0)x*=1+q/100;return Math.ceil(x*100)/100}
function page(a,q,p){const r=q?a.filter(x=>norm(x.name).includes(norm(q))||String(x.id).toLowerCase().includes(String(q).toLowerCase())):a,size=8,total=Math.max(1,Math.ceil(r.length/size)),n=Math.min(Math.max(1,Number(p)||1),total);return{r,total,n,items:r.slice((n-1)*size,n*size)}}
async function showServices(bot,q,s,query='',p=1){const a=await liveServices(s),d=page(a,query,p),rows=d.items.map(x=>[Markup.button.callback('📦 '+x.name,'fsvc:'+s+':'+enc(x.id))]);const nav=[];if(d.n>1)nav.push(Markup.button.callback('⬅ Previous','fpage:'+s+':'+(d.n-1)+':'+enc(query)));if(d.n<d.total)nav.push(Markup.button.callback('Next ➡','fpage:'+s+':'+(d.n+1)+':'+enc(query)));if(nav.length)rows.push(nav);rows.push([Markup.button.callback('🔎 Search Service','fsearch:'+s)]);rows.push([Markup.button.callback('⬅ Servers','ns_user_menu')]);const label=s==='tempo'?'1':s==='vak'?'2':'3',text=query?`🔎 Search Result\n\n🖥 Server ${label}\n\nSearch: ${query}\nFound: ${d.r.length}\nPage ${d.n}/${d.total}`:`📦 Select Service\n\n🖥 Server ${label}\n\nImported Services: ${a.length}\nPage ${d.n}/${d.total}`;if(!d.r.length)rows.unshift([Markup.button.callback('🔎 Search Again','fsearch:'+s)]);if(q?.message?.chat?.id&&q?.message?.message_id)return bot.telegram.editMessageText(q.message.chat.id,q.message.message_id,undefined,text,Markup.inlineKeyboard(rows));return bot.telegram.sendMessage(q,text,Markup.inlineKeyboard(rows))}
async function showAll(bot,q,sel){const rr=await rate(),rows=[],txt=[];for(const[s,label]of [['tempo','🟣 Server 1'],['vak','🔵 Server 2'],['5sim','🟢 Server 3']]){txt.push(`\n${label}`);const svc=await findImportedService(s,sel);if(!svc){txt.push('❌ Service not imported');continue}const a=await liveCountries(s,svc);if(!a.length){txt.push('❌ No live stock');continue}const c=await cfg(s);txt.push(`Available: ${a.length}`);for(const x of a.slice(0,15)){let p=Number(x.p)*rr;const f=Number(c?.profit||c?.profitAmount||0),z=Number(c?.profitPercent||c?.markup||0);if(f||z)p=sell(p,c);else p=Math.ceil(p*100)/100;rows.push([Markup.button.callback(`${label} • 🌍 ${x.name} • ₹${p} • Stock: ${x.stock}`,'fbuy:'+s+':'+enc(x.id)+':'+enc(svc.id))])}}rows.push([Markup.button.callback('⬅ Search Service','fsearch:'+sel.server)]);return bot.telegram.editMessageText(q.message.chat.id,q.message.message_id,undefined,`📦 ${sel.name}\n\n🌍 Available countries (live price & stock):${txt.join('\n')}`,Markup.inlineKeyboard(rows))}
const prev=Telegraf.prototype.handleUpdate;Telegraf.prototype.handleUpdate=async function(u,...args){try{const q=u?.callback_query,cb=q?.data||'',uid=q?.from?.id||u?.message?.from?.id,text=u?.message?.text||'';if(q&&uid){if(['ns_user_5sim','ns_user_vak','tempo_user'].includes(cb)){try{await this.telegram.answerCbQuery(q.id)}catch{};return showServices(this,q,cb==='tempo_user'?'tempo':cb==='ns_user_vak'?'vak':'5sim','',1)}if(cb.startsWith('fsearch:')){const s=cb.slice(8);state.set(String(uid),'search:'+s);try{await this.telegram.answerCbQuery(q.id)}catch{};return this.telegram.sendMessage(uid,'🔎 Search Service\n\nService name ya service ID bheje:')}if(cb.startsWith('fpage:')){const z=cb.split(':'),s=z[1],p=Number(z[2])||1,query=dec(z.slice(3).join(':'));try{await this.telegram.answerCbQuery(q.id)}catch{};return showServices(this,q,s,query,p)}if(cb.startsWith('fsvc:')){const z=cb.split(':'),s=z[1],id=dec(z.slice(2).join(':')),a=await liveServices(s),sel=a.find(x=>String(x.id)===String(id));if(sel){try{await this.telegram.answerCbQuery(q.id)}catch{};return showAll(this,q,{...sel,server:s})}}if(cb.startsWith('fbuy:')){const z=cb.split(':'),s=z[1],country=dec(z[2]),service=dec(z.slice(3).join(':'));try{await this.telegram.answerCbQuery(q.id)}catch{};if(s==='tempo')return prev.call(this,{...u,callback_query:{...q,data:'tempo_buy_'+enc(country)+'_'+enc(service)+'_'+enc(service)}},...args);return prev.call(this,{...u,callback_query:{...q,data:'ns_buy_'+s+'_'+enc(country)+'_'+enc(service)}},...args)}}if(u?.message?.chat?.type==='private'&&uid&&text&&!text.startsWith('/')&&state.has(String(uid))){const v=state.get(String(uid));state.delete(String(uid));if(v.startsWith('search:'))return showServices(this,null,v.slice(7),text.trim(),1)}}catch(e){console.log('IMPORTED CATALOG SEARCH:',e.message)}return prev.call(this,u,...args)};
