const mongoose=require('mongoose');const axios=require('axios');const {Telegraf,Markup}=require('telegraf');
const FB='https://5sim.net/v1',VB='https://vak-sms.com/stubs/handler_api.php',TB='https://api.temporasms.com/stubs/handler_api.php',VK=process.env.VAKSMS_API_KEY||'',TK=process.env.TEMPORASMS_API_KEY||process.env.TEMPO_API_KEY||process.env.TEMPO_SMS_API_KEY||'';
const state=new Map(),cache=new Map();const enc=x=>encodeURIComponent(String(x)),dec=x=>{try{return decodeURIComponent(x)}catch{return String(x)}};
async function cfg(s){try{return await mongoose.connection.db.collection('number_server_configs').findOne({server:s})}catch{return null}}
async function rate(){try{const x=await mongoose.connection.db.collection('settings').findOne({key:'usdtInrRate'}),n=Number(x?.value);return Number.isFinite(n)&&n>0?n:100}catch{return 100}}
async function api(s,a,p={}){if(s==='5sim')return(await axios.get(FB+'/guest/prices',{params:p,timeout:20000,headers:{Accept:'application/json'}})).data;if(s==='vak')return(await axios.get(VB,{params:{action:a,api_key:VK,...p},timeout:20000,headers:{Accept:'application/json'}})).data;if(!TK)throw Error('TemporaSMS API key is not configured');return(await axios.get(TB,{params:{action:a,api_key:TK,...p},timeout:20000,headers:{Accept:'application/json'}})).data}
const norm=x=>String(x??'').trim().toLowerCase().replace(/[^a-z0-9]/g,'');
function importedServices(c){return(c?.services||[]).map(x=>({id:String(x.id??x.code??x.service??x.serviceCode??''),name:String(x.name||x.title||x.serviceName||x.text_en||x.eng||x.rus||x.text||x.service_name||x.id||x.code||x.serviceCode||'')})).filter(x=>x.id&&x.name)}
function addService(out,id,name){id=String(id??'').trim();name=String(name??id).trim();if(!id||!name)return;if(/^(status|success|error|message|code|balance|country|countries|operator|operators|service|services|result|data)$/i.test(id))return;if(!out.has(id))out.set(id,{id,name})}
function parseLiveServices(s,d){const out=new Map();if(!d)return[];if(s==='5sim'){for(const [country,v] of Object.entries(d||{})){if(!v||typeof v!=='object')continue;for(const service of Object.keys(v))addService(out,service,service)}return[...out.values()]}
const consume=(x)=>{if(x==null)return;if(typeof x==='string'){const t=x.trim();if(!t)return;for(const part of t.split(/[,;|\n]+/)){const z=part.trim();if(!z)continue;const m=z.match(/^([^:]+):(.+)$/);addService(out,m?m[1].trim():z,m?m[2].trim():z)}return}if(Array.isArray(x)){for(const v of x){if(typeof v==='string')consume(v);else if(v&&typeof v==='object')consume(v)}return}if(typeof x!=='object')return;
for(const key of ['services','data','result','list','items'])if(x[key]!=null){consume(x[key]);if(out.size)return}
for(const[k,v]of Object.entries(x)){if(v==null)continue;if(typeof v==='string'){addService(out,k,v);continue}if(typeof v==='object'){const id=v.id??v.code??v.service??v.serviceCode??v.key??k;const name=v.name??v.title??v.serviceName??v.text_en??v.eng??v.rus??v.text??v.description??id;addService(out,id,name)}}};consume(d);
if(!out.size&&s!=='5sim'&&d&&typeof d==='object'){for(const k of Object.keys(d)){if(!['status','success','error','message','balance'].includes(k.toLowerCase()))addService(out,k,k)}}return[...out.values()]}
async function liveServices(s){const c=await cfg(s),k='svc:'+s,h=cache.get(k);if(h&&Date.now()-h.t<10000)return h.v;let a=[];try{const d=await api(s,s==='5sim'?'getPrices':'getServices',{});a=parseLiveServices(s,d);console.log('LIVE SERVICES',s,'count=',a.length)}catch(e){console.log('LIVE SERVICES',s,'ERROR=',e.response?.data||e.message)}if(!a.length&&s!=='5sim'){try{const d=await api(s,'getPrices',{});a=parseLiveServices(s,d);console.log('LIVE SERVICES FROM PRICES',s,'count=',a.length)}catch(e){console.log('LIVE SERVICES PRICES',s,'ERROR=',e.response?.data||e.message)}}if(!a.length)a=importedServices(c);cache.set(k,{t:Date.now(),v:a});return a}
function block(v){let p=0,stock=0;const w=o=>{if(!o)return;if(Array.isArray(o))return o.forEach(w);if(typeof o!=='object')return;for(const k of ['cost','price','rate','sell_price','buy_price','Price']){const n=Number(o[k]);if(Number.isFinite(n)&&n>0)p=p?Math.min(p,n):n}for(const k of ['count','stock','qty','quantity','available','Qty']){const n=Number(o[k]);if(Number.isFinite(n)&&n>=0)stock+=n}for(const[k,x]of Object.entries(o))if(!['cost','price','rate','sell_price','buy_price','Price','count','stock','qty','quantity','available','Qty'].includes(k)&&x&&typeof x==='object')w(x)};w(v);return{p,stock}}
function countryName(id,map){const n=map?.get(String(id));if(n)return n;return String(id).replace(/[_-]+/g,' ').replace(/\b\w/g,m=>m.toUpperCase())}
function countries(d,service,names){const out=new Map(),add=(id,v)=>{const b=block(v);if(b.p>0||b.stock>0)out.set(String(id),{id:String(id),name:countryName(id,names),...b})};if(!d)return[];
const svc=String(service),ns=norm(service);const walk=(o)=>{if(!o||typeof o!=='object'||Array.isArray(o))return;for(const[k,v]of Object.entries(o)){if(!v||typeof v!=='object')continue;const nk=norm(k);if(nk===ns){for(const[country,val]of Object.entries(v))add(country,val);continue}if(v[svc]&&typeof v[svc]==='object'){add(k,v[svc]);continue}for(const[sk,sv]of Object.entries(v)){if(norm(sk)===ns&&sv&&typeof sv==='object'){add(k,sv);continue}}walk(v)}};walk(d);return[...out.values()]}
async function liveCountries(s,svc){const c=await cfg(s),key='ct:'+s+':'+svc.id,h=cache.get(key);if(h&&Date.now()-h.t<5000)return h.v;let d=null;try{if(s==='5sim')d=await api(s,'getPrices',{product:svc.id});else d=await api(s,'getPrices',{service:svc.id});console.log('LIVE COUNTRY',s,svc.id,'received',typeof d)}catch(e){console.log('LIVE COUNTRY',s,svc.id,'ERROR=',e.response?.data||e.message)}if((!d||typeof d!=='object')&&s!=='5sim'){try{d=await api(s,'getPrices',{});console.log('LIVE COUNTRY FALLBACK PRICES',s,svc.id)}catch(e){console.log('LIVE COUNTRY FALLBACK',s,e.response?.data||e.message)}}const names=new Map((c?.countries||[]).map(x=>[String(x.id??x.countryId??x.code),String(x.name||x.title||x.text_en||x.eng||x.rus||x.countryName||x.id||x.countryId||x.code)]));let a=countries(d,svc.id,names);cache.set(key,{t:Date.now(),v:a});return a}
async function findImportedService(s,sel){const a=await liveServices(s);return a.find(x=>String(x.id).toLowerCase()===String(sel.id).toLowerCase())||a.find(x=>norm(x.name)===norm(sel.name))}
function sell(p,c){let x=Number(p||0),f=Number(c?.profit||c?.profitAmount||0),q=Number(c?.profitPercent||c?.markup||0);if(f>0)x+=f;if(q>0)x*=1+q/100;return Math.ceil(x*100)/100}
function page(a,q,p){const r=q?a.filter(x=>norm(x.name).includes(norm(q))||String(x.id).toLowerCase().includes(String(q).toLowerCase())):a,size=8,total=Math.max(1,Math.ceil(r.length/size)),n=Math.min(Math.max(1,Number(p)||1),total);return{r,total,n,items:r.slice((n-1)*size,n*size)}}
async function showServices(bot,q,s,query='',p=1,chatId=null){const a=await liveServices(s),d=page(a,query,p),rows=d.items.map(x=>[Markup.button.callback('📦 '+x.name,'fsvc:'+s+':'+enc(x.id))]);const nav=[];if(d.n>1)nav.push(Markup.button.callback('⬅ Previous','fpage:'+s+':'+(d.n-1)+':'+enc(query)));if(d.n<d.total)nav.push(Markup.button.callback('Next ➡','fpage:'+s+':'+(d.n+1)+':'+enc(query)));if(nav.length)rows.push(nav);rows.push([Markup.button.callback('🔎 Search Service','fsearch:'+s)]);rows.push([Markup.button.callback('⬅ Servers','ns_user_menu')]);const label=s==='tempo'?'1':s==='vak'?'2':'3',text=query?`🔎 Search Result\n\n🖥 Server ${label}\n\nSearch: ${query}\nFound: ${d.r.length}\nPage ${d.n}/${d.total}`:`📦 Select Service\n\n🖥 Server ${label}\n\nLive Services: ${a.length}\nPage ${d.n}/${d.total}`;if(!d.r.length)rows.unshift([Markup.button.callback('🔎 Search Again','fsearch:'+s)]);if(q?.message?.chat?.id&&q?.message?.message_id)return bot.telegram.editMessageText(q.message.chat.id,q.message.message_id,undefined,text,Markup.inlineKeyboard(rows));const target=chatId||q?.chat?.id||q?.from?.id;if(!target)throw Error('Search result chat_id missing');return bot.telegram.sendMessage(target,text,Markup.inlineKeyboard(rows))}
async function showAll(bot,q,sel){const rr=await rate(),rows=[],txt=[];for(const[s,label]of [['tempo','🟣 Server 1'],['vak','🔵 Server 2'],['5sim','🟢 Server 3']]){txt.push(`\n${label}`);const svc=await findImportedService(s,sel);if(!svc){txt.push('❌ Service not available');continue}const a=await liveCountries(s,svc);if(!a.length){txt.push('❌ No live country/stock');continue}const c=await cfg(s);txt.push(`Available: ${a.length}`);for(const x of a.slice(0,20)){let p=Number(x.p)*rr;const f=Number(c?.profit||c?.profitAmount||0),z=Number(c?.profitPercent||c?.markup||0);if(f||z)p=sell(p,c);else p=Math.ceil(p*100)/100;rows.push([Markup.button.callback(`${label} • 🌍 ${x.name} • ₹${p} • Stock: ${x.stock}`,'fbuy:'+s+':'+enc(x.id)+':'+enc(svc.id))])}}rows.push([Markup.button.callback('⬅ Search Service','fsearch:'+sel.server)]);return bot.telegram.editMessageText(q.message.chat.id,q.message.message_id,undefined,`📦 ${sel.name}\n\n🌍 Available countries across all servers (LIVE):${txt.join('\n')}`,Markup.inlineKeyboard(rows))}
const prev=Telegraf.prototype.handleUpdate;Telegraf.prototype.handleUpdate=async function(u,...args){try{const q=u?.callback_query,cb=q?.data||'',uid=q?.from?.id||u?.message?.from?.id||u?.message?.chat?.id,text=u?.message?.text||'';if(q&&uid){if(['ns_user_5sim','ns_user_vak','tempo_user'].includes(cb)){try{await this.telegram.answerCbQuery(q.id)}catch{};return showServices(this,q,cb==='tempo_user'?'tempo':cb==='ns_user_vak'?'vak':'5sim','',1,uid)}if(cb.startsWith('fsearch:')){const s=cb.slice(8);state.set(String(uid),'search:'+s);try{await this.telegram.answerCbQuery(q.id)}catch{};return this.telegram.sendMessage(uid,'🔎 Search Service\n\nService name ya service ID bheje:')}if(cb.startsWith('fpage:')){const z=cb.split(':'),s=z[1],p=Number(z[2])||1,query=dec(z.slice(3).join(':'));try{await this.telegram.answerCbQuery(q.id)}catch{};return showServices(this,q,s,query,p,uid)}if(cb.startsWith('fsvc:')){const z=cb.split(':'),s=z[1],id=dec(z.slice(2).join(':')),a=await liveServices(s),sel=a.find(x=>String(x.id)===String(id));if(sel){try{await this.telegram.answerCbQuery(q.id)}catch{};return showAll(this,q,{...sel,server:s})}}if(cb.startsWith('fbuy:')){const z=cb.split(':'),s=z[1],country=dec(z[2]),service=dec(z.slice(3).join(':'));try{await this.telegram.answerCbQuery(q.id)}catch{};if(s==='tempo')return prev.call(this,{...u,callback_query:{...q,data:'tempo_buy_'+enc(country)+'_'+enc(service)+'_'+enc(service)}},...args);return prev.call(this,{...u,callback_query:{...q,data:'ns_buy_'+s+'_'+enc(country)+'_'+enc(service)}},...args)}}if(u?.message?.chat?.type==='private'&&uid&&text&&!text.startsWith('/')&&state.has(String(uid))){const v=state.get(String(uid));state.delete(String(uid));if(v.startsWith('search:'))return showServices(this,null,v.slice(7),text.trim(),1,uid)}}catch(e){console.log('LIVE CATALOG SEARCH:',e.message)}return prev.call(this,u,...args)};
