const mongoose=require('mongoose');const axios=require('axios');const {Telegraf,Markup}=require('telegraf');
const FIVE_BASE='https://5sim.net/v1',FIVE_TOKEN=process.env.FIVESIM_API_KEY||process.env.FIVE_SIM_API_KEY||process.env['5SIM_API_KEY']||'';const VAK_KEY=process.env.VAKSMS_API_KEY||'',VAK_BASE='https://vak-sms.com/stubs/handler_api.php',TEMPO_BASE='https://api.temporasms.com/stubs/handler_api.php',TEMPO_KEY=process.env.TEMPORASMS_API_KEY||process.env.TEMPO_API_KEY||process.env.TEMPO_SMS_API_KEY||'';
const state=new Map(),cache=new Map();const enc=x=>encodeURIComponent(String(x)),dec=x=>{try{return decodeURIComponent(x)}catch{return String(x)}};
async function cfg(server){try{return await mongoose.connection.db.collection('number_server_configs').findOne({server})}catch{return null}}
async function rate(){try{const d=await mongoose.connection.db.collection('settings').findOne({key:'usdtInrRate'});const n=Number(d?.value);return Number.isFinite(n)&&n>0?n:100}catch{return 100}}
async function api(server,action,p={}){if(server==='5sim'){if(!FIVE_TOKEN){}return(await axios.get(FIVE_BASE+'/guest/prices',{params:p,timeout:18000,headers:{Accept:'application/json'}})).data}if(server==='vak')return(await axios.get(VAK_BASE,{params:{action,api_key:VAK_KEY,...p},timeout:18000})).data;if(!TEMPO_KEY)throw new Error('TemporaSMS API key is not configured');return(await axios.get(TEMPO_BASE,{params:{action,api_key:TEMPO_KEY,...p},timeout:18000})).data}
function servicesFrom(data){const out=new Map(),add=(id,name)=>{if(id!=null&&!out.has(String(id)))out.set(String(id),String(name||id))};if(!data)return[];if(Array.isArray(data)){for(const x of data){if(typeof x==='string')add(x,x);else if(x&&typeof x==='object')add(x.id??x.code??x.service??x.key,x.name??x.title??x.serviceName??x.label??x.id)}}else if(typeof data==='object'){if(data.services)return servicesFrom(data.services);if(data.data?.services)return servicesFrom(data.data.services);if(data.result?.services)return servicesFrom(data.result.services);for(const [k,v] of Object.entries(data)){if(v&&typeof v==='object'&&('name' in v||'title' in v||'serviceName' in v||'code' in v))add(v.id??v.code??k,v.name??v.title??v.serviceName??k);else if(typeof v==='string')add(k,v)}}return[...out].map(([id,name])=>({id,name})).filter(x=>x.id&&!['data','result','success'].includes(x.id.toLowerCase()))}
async function getServices(server){const k='svc:'+server,h=cache.get(k);if(h&&Date.now()-h.t<30000)return h.v;let a=[];try{if(server==='5sim'){const d=await api(server,'getPrices');const m=new Map();for(const c of Object.values(d||{}))for(const s of Object.keys(c||{}))m.set(s,s);a=[...m].map(([id,name])=>({id,name}))}else a=servicesFrom(await api(server,'getServices'))}catch(e){console.log('ALL SERVER SERVICES',server,e.message)}if(!a.length){const c=await cfg(server);a=(c?.services||[]).map(x=>({id:String(x.id),name:String(x.name||x.id)}))}cache.set(k,{t:Date.now(),v:a});return a}
function priceBlock(v){let base=0,stock=0;const walk=o=>{if(!o)return;if(Array.isArray(o)){o.forEach(walk);return}if(typeof o!=='object')return;for(const k of ['cost','price','rate','sell_price','buy_price','Price']){const n=Number(o[k]);if(Number.isFinite(n)&&n>0)base=base?Math.min(base,n):n}for(const k of ['count','stock','qty','quantity','available','Qty']){const n=Number(o[k]);if(Number.isFinite(n)&&n>=0)stock+=n}for(const [k,x] of Object.entries(o))if(!['cost','price','rate','sell_price','buy_price','Price','count','stock','qty','quantity','available','Qty'].includes(k)&&x&&typeof x==='object')walk(x)};walk(v);return{base,stock}}
function countriesFrom(data,service){const out=[];if(!data||typeof data!=='object')return out;const add=(id,block)=>{const p=priceBlock(block);if(p.base>0||p.stock>0)out.push({id:String(id),...p})};if(data[service]&&typeof data[service]==='object'){for(const [id,b] of Object.entries(data[service]))add(id,b);return out}const walk=(o,d=0)=>{if(!o||typeof o!=='object'||d>8)return;if(o[service]&&typeof o[service]==='object'){for(const [id,b] of Object.entries(o[service]))add(id,b);return}for(const v of Object.values(o))if(v&&typeof v==='object')walk(v,d+1)};walk(data);return out}
async function getCountries(server,service){const k='ct:'+server+':'+service,h=cache.get(k);if(h&&Date.now()-h.t<15000)return h.v;let d=null;try{d=server==='5sim'?await api(server,'getPrices',{product:service}):await api(server,'getPrices',{service})}catch(e){console.log('ALL SERVER COUNTRIES',server,service,e.message)}const a=countriesFrom(d,service),c=await cfg(server),names=new Map((c?.countries||[]).map(x=>[String(x.id),x.name]));for(const x of a)x.name=names.get(x.id)||x.id;x.a=a.sort((x,y)=>String(x.name).localeCompare(String(y.name)));cache.set(k,{t:Date.now(),v:a});return a}
function norm(s){return String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,'')}
async function matchService(server,selected){const all=await getServices(server),id=all.find(x=>String(x.id).toLowerCase()===String(selected.id).toLowerCase());if(id)return id;const n=norm(selected.name),exact=all.find(x=>norm(x.name)===n);return exact||null}
function sell(base,c){let p=Number(base||0);const fixed=Number(c?.profit||c?.profitAmount||0),pct=Number(c?.profitPercent||c?.markup||0);if(fixed>0)p+=fixed;if(pct>0)p*=1+pct/100;return Math.ceil(p*100)/100}
async function renderServices(bot,q,server,query=''){const all=await getServices(server),a=query?all.filter(x=>norm(x.name).includes(norm(query))||String(x.id).toLowerCase().includes(String(query).toLowerCase())):all,n=8,rows=a.slice(0,n).map(s=>[Markup.button.callback('📦 '+s.name,'allsvc:'+server+':'+enc(s.id))]);rows.push([Markup.button.callback('🔎 Search Service','allsvcsearch:'+server)]);rows.push([Markup.button.callback('⬅ Servers','ns_user_menu')]);return bot.telegram.editMessageText(q.message.chat.id,q.message.message_id,undefined,`📦 Select Service\n\n🖥 Server ${server==='tempo'?'1':server==='vak'?'2':'3'}\n\n${query?'🔎 Result for: '+query+'\n\nFound: '+a.length:'Live services: '+all.length}`,Markup.inlineKeyboard(rows))}
async function renderAllCountries(bot,q,selected){const servers=[['tempo','🟣 Server 1'],['vak','🔵 Server 2'],['5sim','🟢 Server 3']],r=await rate(),lines=[],rows=[];for(const [server,label] of servers){const svc=await matchService(server,selected);lines.push(`\n${label}`);if(!svc){lines.push('❌ Service not available');continue}const cs=await getCountries(server,svc.id),c=await cfg(server);if(!cs.length){lines.push('❌ No country/stock available');continue}lines.push(`Available: ${cs.length}`);for(const x of cs.slice(0,12)){let p=Number(x.base||0)*r;const fixed=Number(c?.profit||c?.profitAmount||0),pct=Number(c?.profitPercent||c?.markup||0);if(fixed||pct)p=sell(p,c);else p=Math.ceil(p*100)/100;rows.push([Markup.button.callback(`${label} • 🌍 ${x.name} • ₹${p} • Stock: ${x.stock}`,'allbuy:'+server+':'+enc(x.id)+':'+enc(svc.id))])}}rows.push([Markup.button.callback('⬅ Service Search','allsvcsearch:'+selected.server)]);return bot.telegram.editMessageText(q.message.chat.id,q.message.message_id,undefined,`🌍 ${selected.name}\n\nCountries available across all servers:${lines.join('\n')}`,Markup.inlineKeyboard(rows))}
const previous=Telegraf.prototype.handleUpdate;Telegraf.prototype.handleUpdate=async function(update,...args){try{const q=update?.callback_query,cb=q?.data||'',uid=q?.from?.id,text=update?.message?.text||'';if(q&&uid){if(cb.startsWith('allsvcsearch:')){const server=cb.slice(13);state.set(String(uid),'search:'+server);try{await this.telegram.answerCbQuery(q.id)}catch{};return this.telegram.sendMessage(uid,'🔎 Search Service\n\nService ka name ya service ID bheje:')}if(cb.startsWith('allsvc:')){const z=cb.split(':'),server=z[1],id=dec(z.slice(2).join(':'));const all=await getServices(server),selected=all.find(x=>String(x.id)===String(id));if(selected){try{await this.telegram.answerCbQuery(q.id)}catch{};return renderAllCountries(this,q,{...selected,server})}}if(cb.startsWith('allbuy:')){const z=cb.split(':'),server=z[1],country=dec(z[2]),service=dec(z.slice(3).join(':'));try{await this.telegram.answerCbQuery(q.id)}catch{};if(server==='tempo')return previous.call(this,{...update,callback_query:{...q,data:'tempo_buy_'+enc(country)+'_'+enc(service)+'_'+enc(service)}},...args);return previous.call(this,{...update,callback_query:{...q,data:'ns_buy_'+server+'_'+enc(country)+'_'+enc(service)}},...args)}}if(update?.message?.chat?.type==='private'&&uid&&text&&!text.startsWith('/')&&state.has(String(uid))){const st=state.get(String(uid));state.delete(String(uid));if(st.startsWith('search:'))return renderServices(this,{message:{chat:{id:uid,message_id:0}},...{}},st.slice(7),text)}if(q&&uid&&['ns_user_5sim','ns_user_vak','tempo_user'].includes(cb)){try{await this.telegram.answerCbQuery(q.id)}catch{};return renderServices(this,q,cb==='tempo_user'?'tempo':cb==='ns_user_vak'?'vak':'5sim')}}catch(e){console.log('ALL SERVER SERVICE/COUNTRY BOOT:',e.message)}return previous.call(this,update,...args)};
