const mongoose=require('mongoose');const {Telegraf,Markup}=require('telegraf');
const OWNER_ID=5087094625,states=new Map();
const S={tempo:{label:'1',name:'TemporaSMS'},vak:{label:'2',name:'VAK-SMS'},'5sim':{label:'3',name:'5SIM'}};
const enc=x=>encodeURIComponent(String(x)),dec=x=>{try{return decodeURIComponent(x)}catch{return String(x)}};
async function db(){return mongoose.connection.db.collection('number_server_configs')}
async function cfg(s){return (await db()).findOne({server:s})}
async function allCfg(){const a=await (await db()).find({server:{$in:['tempo','vak','5sim']}}).toArray();const m=new Map(a.map(x=>[x.server,x]));return ['tempo','vak','5sim'].map(s=>[s,m.get(s)||{server:s,countries:[],services:[]}])}
function norm(x){return String(x??'').trim().toLowerCase().replace(/[^a-z0-9]/g,'')}
function servicesOf(c){return Array.isArray(c?.services)?c.services.filter(x=>x&&String(x.id??x.code??'').trim()):[]}
function countriesOf(c){return Array.isArray(c?.countries)?c.countries.filter(x=>x&&String(x.id??x.code??'').trim()):[]}
function serviceMatch(x,q){return !q||norm(x.name).includes(norm(q))||norm(x.id??x.code).includes(norm(q))}
function serviceId(x){return String(x.id??x.code??x.service??x.service_id??'')}
function countryId(x){return String(x.id??x.code??x.countryId??x.country_id??'')}
function serviceName(x){return String(x.name||x.title||x.serviceName||x.text_en||x.eng||x.rus||serviceId(x))}
function countryName(x){return String(x.name||x.title||x.countryName||x.text_en||x.eng||x.rus||countryId(x))}
async function unionServices(q=''){const rows=[];for(const [s,c] of await allCfg()){for(const x of servicesOf(c)){if(!serviceMatch(x,q))continue;const id=serviceId(x),hit=rows.find(v=>norm(v.id)===norm(id));if(hit)hit.servers.push(s);else rows.push({id,name:serviceName(x),servers:[s]})}}return rows.sort((a,b)=>a.name.localeCompare(b.name))}
function serviceIn(c,id){return servicesOf(c).find(x=>norm(serviceId(x))===norm(id))}
function label(s){return S[s]?.label||s}
async function showCatalog(bot,uid,q=''){const rows0=await unionServices(q),rows=rows0.slice(0,12).map(x=>[Markup.button.callback('📦 '+x.name+' • '+x.servers.map(label).map(n=>'S'+n).join('/'),'acsvc:'+enc(x.id))]);rows.push([Markup.button.callback('🔎 Search Service','acsearch')]);rows.push([Markup.button.callback('⬅ Servers','ns_user_menu')]);return bot.telegram.sendMessage(uid,q?`🔎 Service Search\n\nSearch: ${q}\nFound: ${rows0.length}`:`📦 Select Service\n\nAll imported services • Server 1/2/3\nTotal: ${rows0.length}`,Markup.inlineKeyboard(rows))}
async function showService(bot,q,sid){const all=await allCfg(),rows=[];for(const [s,c] of all){const svc=serviceIn(c,sid);if(!svc)continue;const cs=countriesOf(c);for(const co of cs.slice(0,50)){const cid=countryId(co),price=Number(svc.price||0);let text=`🖥 Server ${label(s)} • 🌍 ${countryName(co)}`;if(price>0)text+=` • ₹${price}`;rows.push([Markup.button.callback(text,'fbuy:'+s+':'+enc(cid)+':'+enc(serviceId(svc)))]);}}if(!rows.length){return bot.telegram.editMessageText(q.message.chat.id,q.message.message_id,undefined,'❌ This service is not available in any imported server.',Markup.inlineKeyboard([[Markup.button.callback('⬅ Services','acroot')]]))}const names=all.map(([s,c])=>{const x=serviceIn(c,sid);return x?`${S[s].name}: ${serviceName(x)}`:null}).filter(Boolean);rows.push([Markup.button.callback('⬅ Services','acroot')]);return bot.telegram.editMessageText(q.message.chat.id,q.message.message_id,undefined,`📦 ${names[0]||sid}\n\n${names.join('\n')}\n\n🌍 Available countries: ${rows.length-1}`,Markup.inlineKeyboard(rows))}
const prev=Telegraf.prototype.handleUpdate;Telegraf.prototype.handleUpdate=async function(u,...args){try{const q=u?.callback_query,cb=q?.data||'',uid=q?.from?.id||u?.message?.from?.id,text=u?.message?.text||'';if(q&&uid){if(['tempo_user','ns_user_vak','ns_user_5sim'].includes(cb)){try{await this.telegram.answerCbQuery(q.id)}catch{};return showCatalog(this,uid)}if(cb==='acroot'){try{await this.telegram.answerCbQuery(q.id)}catch{};return showCatalog(this,uid)}if(cb==='acsearch'){states.set(String(uid),'search');try{await this.telegram.answerCbQuery(q.id)}catch{};return this.telegram.sendMessage(uid,'🔎 Search Service\n\nService name ya service ID bheje:')}if(cb.startsWith('acsvc:')){try{await this.telegram.answerCbQuery(q.id)}catch{};return showService(this,q,dec(cb.slice(6)))}if(cb.startsWith('fsearch2:')){states.set(String(uid),'search');try{await this.telegram.answerCbQuery(q.id)}catch{};return this.telegram.sendMessage(uid,'🔎 Search Service\n\nService name ya service ID bheje:')}}if(uid&&text&&!text.startsWith('/')&&states.get(String(uid))==='search'){states.delete(String(uid));return showCatalog(this,uid,text.trim())}}catch(e){console.log('UNIFIED CATALOG ERROR:',e.message)}return prev.call(this,u,...args)};
