const mongoose=require('mongoose');
const axios=require('axios');
const {Telegraf,Markup}=require('telegraf');
const OWNER_ID=5087094625;
const TBASE='https://api.temporasms.com/stubs/handler_api.php';
const TKEY=process.env.TEMPORASMS_API_KEY||process.env.TEMPO_API_KEY||process.env.TEMPO_SMS_API_KEY||'';
const schema=new mongoose.Schema({server:{type:String,unique:true},countries:{type:Array,default:[]},services:{type:Array,default:[]},operators:{type:Array,default:[]},markup:{type:Number,default:0}},{collection:'number_server_configs'});
const Config=mongoose.models.NumberServerConfig||mongoose.models.TempoAdminFinalConfig||mongoose.model('TempoAdminFinalConfig',schema);
async function admin(id){if(Number(id)===OWNER_ID)return true;try{return !!(await mongoose.models.Admin?.findOne({userId:String(id)}));}catch{return false;}}
async function cfg(){return Config.findOneAndUpdate({server:'tempo'},{server:'tempo'},{upsert:true,new:true,setDefaultsOnInsert:true});}
async function tempo(action,params={}){if(!TKEY)throw Error('TempoSMS API key is not configured');const r=await axios.get(TBASE,{params:{api_key:TKEY,action,...params},timeout:20000,headers:{Accept:'application/json'}});return r.data}
function arrFrom(d){if(Array.isArray(d))return d;if(d&&Array.isArray(d.services))return d.services;if(d&&Array.isArray(d.data))return d.data;if(d&&Array.isArray(d.result))return d.result;if(d&&typeof d==='object')return Object.entries(d).filter(([k])=>!['status','error','message'].includes(k.toLowerCase())).map(([id,v])=>({id,name:typeof v==='string'?v:(v?.name||v?.title||v?.eng||v?.text||id),code:v?.code||id}));return[];}
function countryList(d){return arrFrom(d).map((v,i)=>({id:String(v?.id??v?.code??i),name:String(v?.name||v?.name_en||v?.eng||v?.title||v?.text||v?.rus||v?.id||i),code:String(v?.iso2||v?.iso||v?.code||v?.id||i)})).filter(x=>x.name&&x.name!=='undefined');}
function serviceList(d){return arrFrom(d).map((v,i)=>({id:String(v?.code??v?.id??v?.service??i),name:String(v?.name||v?.title||v?.eng||v?.text||v?.name_en||v?.id||v?.code||i)})).filter(x=>x.name&&x.name!=='undefined');}
async function getOperatorCandidates(){try{const d=await tempo('getOperators');const a=arrFrom(d).map(v=>String(v?.id??v?.code??v)).filter(Boolean);return [...new Set(['1',...a])];}catch{return ['1'];}}
async function syncCountries(){const c=await cfg();let last='';for(const op of await getOperatorCandidates()){try{const a=countryList(await tempo('getCountries',{operator:op}));if(a.length){c.countries=a;await c.save();return a.length;}}catch(e){last=e.message}}throw Error('TemporaSMS countries API returned no countries'+(last?` (${last})`:''));}
async function syncServices(){const c=await cfg();let last='';for(const op of await getOperatorCandidates()){try{const a=serviceList(await tempo('getServices',{operator:op}));if(a.length){const old=new Map(c.services.map(x=>[String(x.id),Number(x.price||0)]));c.services=a.map(x=>({...x,price:old.get(String(x.id))||0}));await c.save();return a.length;}}catch(e){last=e.message}}throw Error('TemporaSMS services API returned no services'+(last?` (${last})`:''));}
async function send(bot,uid,text,extra){return bot.telegram.callApi('sendMessage',{chat_id:uid,text,...(extra||{})});}
function adminMenu(){return Markup.inlineKeyboard([[Markup.button.callback('💰 Get Balance','tempo_admin_balance'),Markup.button.callback('📡 Operators','tempo_admin_ops')],[Markup.button.callback('🔄 Sync Countries','tempo_admin_countries'),Markup.button.callback('🔄 Sync Services','tempo_admin_services')],[Markup.button.callback('💲 Live Prices','tempo_admin_prices'),Markup.button.callback('📋 Countries List','tempo_admin_cl')],[Markup.button.callback('📦 Services List','tempo_admin_sl'),Markup.button.callback('📈 Set Markup %','tempo_admin_markup')],[Markup.button.callback('🗑 Remove All','tempo_admin_remove')],[Markup.button.callback('⬅ Number Servers','admin_servers')]]);}
const previous=Telegraf.prototype.handleUpdate;
Telegraf.prototype.handleUpdate=async function(update,...args){try{const q=update?.callback_query,uid=q?.from?.id,cb=q?.data||'';if(uid&&await admin(uid)){
if(cb==='admin_servers'){try{await this.telegram.answerCbQuery(q.id)}catch{};return send(this,uid,'🖥 NUMBER SERVERS ADMIN\n\nConfigure each server separately.',{reply_markup:Markup.inlineKeyboard([[Markup.button.callback('🟣 Server 1 • TemporaSMS','tempo_settings')],[Markup.button.callback('🔵 Server 2 • VAK-SMS','ns_vak')],[Markup.button.callback('🟢 Server 3 • 5SIM','ns_5sim')],[Markup.button.callback('⬅ Admin Panel','admin_panel')]]).reply_markup});}
if(cb==='tempo_settings'){try{await this.telegram.answerCbQuery(q.id)}catch{};const c=await cfg();return send(this,uid,`⚙️ SERVER 1 • TEMPOSMS SETTINGS\n\nCountries: ${c.countries.length}\nServices: ${c.services.length}\nMarkup: ${c.markup||0}%`,{reply_markup:adminMenu().reply_markup});}
if(cb==='tempo_admin_remove'){const c=await cfg();c.countries=[];c.services=[];c.operators=[];await c.save();try{await this.telegram.answerCbQuery(q.id,'Removed')}catch{};return send(this,uid,'✅ All imported countries & services removed from Server 1.');}
if(cb==='tempo_admin_countries'){try{await this.telegram.answerCbQuery(q.id,'⏳ Syncing countries...')}catch{};try{const n=await syncCountries();return send(this,uid,`✅ Countries synced from Server 1.\n\n🌍 Countries: ${n}`)}catch(e){return send(this,uid,'❌ Country sync failed.\n\n'+e.message)}}
if(cb==='tempo_admin_services'){try{await this.telegram.answerCbQuery(q.id,'⏳ Syncing services...')}catch{};try{const n=await syncServices();return send(this,uid,`✅ Services synced from Server 1.\n\n📦 Services: ${n}`)}catch(e){return send(this,uid,'❌ Service sync failed.\n\n'+e.message)}}
if(cb==='tempo_admin_cl'){const c=await cfg();return send(this,uid,'🌍 Server 1 • Countries\n\n'+(c.countries.map(x=>`${x.id} = ${x.name}`).join('\n')||'None').slice(0,3900));}
if(cb==='tempo_admin_sl'){const c=await cfg();return send(this,uid,'📦 Server 1 • Services\n\n'+(c.services.map(x=>`${x.id} = ${x.name}`).join('\n')||'None').slice(0,3900));}
}}catch(e){console.log('TEMPO ADMIN FINAL FIX:',e.message)}return previous.call(this,update,...args)};
