const mongoose=require('mongoose');const {Telegraf,Markup}=require('telegraf');
const enc=x=>encodeURIComponent(String(x)),dec=x=>{try{return decodeURIComponent(x)}catch{return String(x)}};const norm=x=>String(x??'').toLowerCase().replace(/[^a-z0-9]/g,'');
async function cfg(){return mongoose.connection.db.collection('number_server_configs').findOne({server:'tempo'})}
async function rate(){try{const x=await mongoose.connection.db.collection('settings').findOne({key:'usdtInrRate'});return Number(x?.value)>0?Number(x.value):100}catch{return 100}}
function sell(p,c,r){let x=Number(p||0)*r,q=Number(c?.markup||c?.profitPercent||0);if(q>0)x*=1+q/100;return Math.ceil(x*100)/100}
function find(a,q){q=norm(q);return(a||[]).filter(x=>!q||norm(x.name).includes(q)||String(x.id).toLowerCase().includes(String(q).toLowerCase()))}
function offers(c,cid,sid){return(c?.availability||[]).filter(x=>String(x.countryId)===String(cid)&&String(x.serviceId)===String(sid))}
const prev=Telegraf.prototype.handleUpdate;Telegraf.prototype.handleUpdate=async function(u,...args){try{const q=u?.callback_query,cb=q?.data||'',uid=q?.from?.id;if(q&&uid){if(cb==='tempo_user'){try{await this.telegram.answerCbQuery(q.id)}catch{};const c=await cfg();if(!c)return this.telegram.sendMessage(uid,'❌ Server 1 is not synced yet.');const a=(c.services||[]).slice().sort((x,y)=>String(x.name).localeCompare(String(y.name)));const r=await rate(),rows=a.slice(0,8).map(x=>[Markup.button.callback(`📦 ${x.name} • ₹${sell(x.price,c,r)} • Stock: ${Number(x.stock||0)}`,'fsvc:tempo:'+enc(x.id))]);rows.push([Markup.button.callback('🔎 Search Service','fsearch2:tempo')],[Markup.button.callback('⬅ Servers','ns_user_menu')]);return this.telegram.sendMessage(uid,`📦 Select Service\n\n🖥 Server 1 • TemporaSMS\n\nImported Services: ${a.length}\n📌 Data source: Last Import/Sync`,Markup.inlineKeyboard(rows))}
if(cb.startsWith('fsvc:tempo:')){const sid=dec(cb.slice(11));try{await this.telegram.answerCbQuery(q.id)}catch{};const c=await cfg();if(!c)return;const svc=(c.services||[]).find(x=>String(x.id)===String(sid))||{id:sid,name:sid};const r=await rate(),a=(c.countries||[]).map(x=>{const os=offers(c,x.id,sid);const prices=os.map(o=>Number(o.price)).filter(n=>n>0),stock=os.reduce((n,o)=>n+Number(o.stock||0),0);return{...x,price:prices.length?Math.min(...prices):Number(svc.price||0),stock}}).filter(x=>x.stock>0||x.price>0).sort((a,b)=>String(a.name).localeCompare(String(b.name)));const rows=a.slice(0,50).map(x=>[Markup.button.callback(`🌍 ${x.name} • ₹${sell(x.price,c,r)} • Stock: ${x.stock}`,'fbuy:tempo:'+enc(x.id)+':'+enc(svc.id))]);if(!rows.length)rows.push([Markup.button.callback('❌ No imported stock/price','fsvc:tempo:'+enc(sid))]);rows.push([Markup.button.callback('⬅ Services','nsfix:tempo')]);return this.telegram.editMessageText(q.message.chat.id,q.message.message_id,undefined,`📦 ${svc.name}\n\n🖥 Server 1 • TemporaSMS\n\n🌍 Imported countries: ${a.length}\n📌 Price & Stock: Last Import/Sync`,Markup.inlineKeyboard(rows))}}}catch(e){console.log('TEMPO IMPORTED CATALOG ERROR',e.message)}return prev.call(this,u,...args)};
