const mongoose=require('mongoose');const axios=require('axios');const {Telegraf}=require('telegraf');
const OWNER_ID=5087094625,BASE='https://api.temporasms.com/stubs/handler_api.php',KEY=process.env.TEMPORASMS_API_KEY||process.env.TEMPO_API_KEY||process.env.TEMPO_SMS_API_KEY||'';
const schema=new mongoose.Schema({server:{type:String,unique:true},countries:{type:Array,default:[]},services:{type:Array,default:[]},operators:{type:Array,default:[]},availability:{type:Array,default:[]},markup:{type:Number,default:0}},{collection:'number_server_configs'});const Config=mongoose.models.TempoImportSyncConfig||mongoose.models.NumberServerConfig||mongoose.model('TempoImportSyncConfig',schema);
async function cfg(){return Config.findOneAndUpdate({server:'tempo'},{server:'tempo'},{upsert:true,new:true,setDefaultsOnInsert:true})}
async function api(action,params={}){if(!KEY)throw Error('TEMPORASMS_API_KEY is not configured');return(await axios.get(BASE,{params:{api_key:KEY,action,...params},timeout:30000,headers:{Accept:'application/json'}})).data}
const raw=d=>{if(typeof d==='string'){try{return JSON.parse(d)}catch{return d}}return d};const obj=x=>x&&typeof x==='object'&&!Array.isArray(x);
function arr(d,type){d=raw(d);if(Array.isArray(d))return d;if(d?.[type])return arr(d[type],type);if(d?.data)return arr(d.data,type);if(d?.result)return arr(d.result,type);if(obj(d))return Object.entries(d).filter(([k])=>!['status','success','error','message','code','balance'].includes(k.toLowerCase())).map(([id,v])=>obj(v)?{...v,id:v.id??v.code??id}:v);return[]}
function normCountry(v,i){return{id:String(v?.id??v?.code??v?.iso2??v?.country_id??i),name:String(v?.name||v?.name_en||v?.eng||v?.text_en||v?.title||v?.text||v?.rus||v?.id||v?.code||i),code:String(v?.code||v?.iso2||v?.iso||v?.id||i)}}
function normService(v,i){return{id:String(v?.code??v?.id??v?.service_id??v?.service??i),name:String(v?.name||v?.title||v?.eng||v?.text_en||v?.text||v?.name_en||v?.rus||v?.id||v?.code||i)}}
async function ops(){try{const d=raw(await api('getOperators'));const a=Array.isArray(d)?d:obj(d)?Object.entries(d).map(([k,v])=>obj(v)?(v.id??v.code??v.operator??k):(v??k)):[];return[...new Set(['1','auto','best',...a.map(x=>String(obj(x)?(x.id??x.code??x.operator??x.value??x.name):x)).filter(Boolean)])]}catch{return['1','auto','best']}}
async function countries(){let last='';for(const op of await ops())for(const p of [{operator:op},{operator:op,lang:'en'},{}])try{const a=arr(await api('getCountries',p),'countries').map(normCountry).filter(x=>x.name&&x.name!=='undefined');if(a.length)return[...new Map(a.map(x=>[x.id,x])).values()]}catch(e){last=e.response?.data?.message||e.response?.data||e.message}throw Error('TemporaSMS countries import failed'+(last?' ('+String(last)+')':''))}
async function getServices(cs){for(const p of [{},{lang:'en'},...cs.slice(0,5).map(x=>({country:x.id})),...cs.slice(0,5).map(x=>({country:x.code}))])try{const a=arr(await api('getServices',p),'services').map(normService).filter(x=>x.name&&x.name!=='undefined');if(a.length)return[...new Map(a.map(x=>[x.id,x])).values()]}catch{}return[]}
function leaf(v){return obj(v)&&['cost','price','rate','sell_price','buy_price','count','stock','qty','quantity','available'].some(k=>v[k]!=null)}
function nums(v,keys){let out=[];const walk=o=>{if(!o)return;if(Array.isArray(o))return o.forEach(walk);if(obj(o)){for(const k of keys){const n=Number(o[k]);if(Number.isFinite(n)&&n>=0)out.push(n)}Object.entries(o).forEach(([k,x])=>{if(!keys.includes(k)&&obj(x))walk(x)})}};walk(v);return out}
function extract(tree,countrySet,serviceSet){const out=new Map();const walk=(o,path=[])=>{if(!obj(o)||path.length>8)return;for(const [k,v] of Object.entries(o)){const p=path.concat(String(k));if(leaf(v)){let country=null,service=null;if(p.length>=2){for(const x of p){if(countrySet.has(x))country=x;if(serviceSet.has(x))service=x}}if(!country||!service){country=p[0];service=p[1]}if(country&&service){const prices=nums(v,['cost','price','rate','sell_price','buy_price']);const stocks=nums(v,['count','stock','qty','quantity','available']);const price=prices.filter(n=>n>0).sort((a,b)=>a-b)[0]||0;const stock=stocks.reduce((a,b)=>a+b,0);const operator=String(v.operator||v.operatorId||v.providerId||p[2]||'auto');if(price>0||stock>0){const key=country+'|'+service+'|'+operator;const old=out.get(key);if(!old||((price>0&&price<old.price)||stock>old.stock))out.set(key,{countryId:String(country),serviceId:String(service),price,stock,operator})}}continue}if(obj(v))walk(v,p)}};walk(raw(tree));return[...out.values()]}
async function priceTrees(operators){const trees=[];for(const action of ['getPricesV3','getPricesV2'])try{const d=raw(await api(action,{}));if(obj(d)){trees.push(d);console.log('TEMPO IMPORT PRICE SOURCE',action);return trees}}catch(e){console.log('TEMPO IMPORT',action,e.response?.data||e.message)}for(const op of operators)try{const d=raw(await api('getPrices',{operator:op}));if(obj(d))trees.push(d)}catch(e){console.log('TEMPO IMPORT operator price',op,e.response?.data||e.message)}if(!trees.length)try{const d=raw(await api('getPrices',{}));if(obj(d))trees.push(d)}catch(e){}return trees}
async function sync(){const c=await cfg(),cs=await countries();let ss=await getServices(cs);const ops0=await ops(),countrySet=new Set(cs.map(x=>String(x.id))),serviceSet=new Set(ss.map(x=>String(x.id)));const trees=await priceTrees(ops0);let availability=[];for(const t of trees)availability.push(...extract(t,countrySet,serviceSet));availability=[...new Map(availability.map(x=>[x.countryId+'|'+x.serviceId+'|'+x.operator,x])).values()].slice(0,20000);if(!ss.length){const sm=new Map();for(const x of availability)if(!sm.has(x.serviceId))sm.set(x.serviceId,{id:x.serviceId,name:x.serviceId});ss=[...sm.values()]}const old=new Map((c.services||[]).map(x=>[String(x.id),x]));const bySvc=new Map();for(const x of availability){const a=bySvc.get(x.serviceId)||[];a.push(x);bySvc.set(x.serviceId,a)}ss=ss.map(x=>{const a=bySvc.get(String(x.id))||[];const prices=a.map(y=>y.price).filter(n=>n>0);return{...x,price:prices.length?Math.min(...prices):Number(old.get(String(x.id))?.price||0),stock:a.reduce((n,y)=>n+Number(y.stock||0),0)}});c.countries=cs;c.services=ss;c.operators=ops0.map(x=>({id:String(x),operator:String(x)}));await c.save();await mongoose.connection.db.collection('number_server_configs').updateOne({server:'tempo'},{$set:{availability}});return{countries:cs.length,services:ss.length,operators:c.operators.length,availability:availability.length}}
function admin(id){return Number(id)===OWNER_ID}const prev=Telegraf.prototype.handleUpdate;Telegraf.prototype.handleUpdate=async function(update,...args){const q=update?.callback_query,cb=q?.data||'',uid=q?.from?.id;if(q&&uid&&admin(uid)&&cb==='nsi_import_tempo'){try{await this.telegram.answerCbQuery(q.id,'⏳ Syncing TemporaSMS catalog...')}catch{}try{const r=await sync();return this.telegram.sendMessage(uid,`✅ Server 1 • TemporaSMS Import/Sync completed\n\n🌍 Countries: ${r.countries}\n📦 Services: ${r.services}\n📡 Operators: ${r.operators}\n📊 Price/Stock entries: ${r.availability}`)}catch(e){console.log('TEMPO IMPORT SYNC ERROR:',e.response?.data||e.message);return this.telegram.sendMessage(uid,'❌ Server 1 sync failed.\n\n'+e.message)}}return prev.call(this,update,...args)};
