const mongoose=require('mongoose');const axios=require('axios');const {Telegraf,Markup}=require('telegraf');
const VAK_KEY=process.env.VAKSMS_API_KEY||'',VB='https://vak-sms.com/stubs/handler_api.php',FB='https://5sim.net/v1';const st=new Map();
const S=new mongoose.Schema({server:String,countries:Array,services:Array,operators:Array,markup:Number},{collection:'number_server_configs'});const C=mongoose.models.UserCatalogSearchFix||mongoose.model('UserCatalogSearchFix',S);
async function cfg(server){return C.findOneAndUpdate({server},{server},{upsert:true,new:true,setDefaultsOnInsert:true})}function enc(x){return encodeURIComponent(String(x))}function dec(x){try{return decodeURIComponent(x)}catch{return String(x)}}
async function get(url,p={}){try{return(await axios.get(url,{params:p,timeout:12000})).data}catch{return null}}async function vak(a,p={}){return get(VB,{action:a,api_key:VAK_KEY,...p})}async function five(p){return get(FB+p)}
function country(id,v){v=v&&typeof v==='object'?v:{};return{id:String(v.id??id),name:String(v.name||v.text_en||v.eng||v.title||v.rus||id),code:String(v.iso||v.iso2||v.code||'')}}
function service(id,v){v=v&&typeof v==='object'?v:{};return{id:String(v.id??v.code??v.service??id),name:String(v.name||v.title||v.text_en||v.eng||v.rus||id)}}
const p5={tg:'Telegram',wa:'WhatsApp',go:'Google',ig:'Instagram',fb:'Facebook',tw:'Twitter',vk:'VKontakte',vi:'Viber',wb:'WeChat',ds:'Discord',am:'Amazon',av:'Avito',ok:'Odnoklassniki',ub:'Uber',oi:'OpenAI',nf:'Netflix'};function pname(x){x=String(x);return p5[x.toLowerCase()]||x.replace(/[_-]+/g,' ').replace(/\b\w/g,m=>m.toUpperCase())}
function filt(a,q){q=String(q||'').toLowerCase().trim();return a.filter(x=>!q||String(x.name).toLowerCase().includes(q)||String(x.id).toLowerCase().includes(q)||String(x.code||'').toLowerCase().includes(q))}
async function refresh(server){const c=await cfg(server);if(server==='5sim'){const d=await five('/guest/countries');if(d&&typeof d==='object'){const m=new Map(Object.entries(d).map(([id,v])=>{const x=country(id,v);return[x.id,x.name]}));c.countries=c.countries.map(x=>({...x,name:m.get(String(x.id))||x.name||x.id}))}c.services=c.services.map(x=>({...x,name:x.name&&/^[a-z0-9_-]+$/i.test(x.name)?pname(x.id):x.name||pname(x.id)}));await c.save();return c}
let d=await vak('getCountries');const cm=new Map();if(Array.isArray(d))d.forEach((v,i)=>{const x=country(v?.id??i,v);cm.set(x.id,x.name)});else if(d&&typeof d==='object')Object.entries(d).forEach(([id,v])=>{const x=country(id,v);cm.set(x.id,x.name)});if(cm.size)c.countries=c.countries.map(x=>({...x,name:cm.get(String(x.id))||x.name||x.id}));d=await vak('getServices');if(!d)d=await vak('getServicesList');let a=[];if(Array.isArray(d))a=d;else if(Array.isArray(d?.services))a=d.services;else if(d&&typeof d==='object')a=Object.entries(d).map(([id,v])=>({id,...(v&&typeof v==='object'?v:{name:v})}));if(a.length){const sm=new Map(a.map((v,i)=>{const x=service(v?.id??v?.code??i,v);return[x.id,x.name]}));c.services=c.services.map(x=>({...x,name:sm.get(String(x.id))||x.name||x.id}))}await c.save();return c}
async function countries(bot,q,server,page=1,query=''){const c=await refresh(server),a=filt(c.countries,query),tot=Math.max(1,Math.ceil(a.length/6));page=Math.max(1,Math.min(page,tot));const rows=a.slice((page-1)*6,page*6).map(x=>[Markup.button.callback('🌍 '+x.name,'ucf_country_'+server+'_'+enc(x.id))]);const nav=[];if(page>1)nav.push(Markup.button.callback('⬅','ucf_countries_'+server+'_'+(page-1)+(query?'_'+enc(query):'')));if(page<tot)nav.push(Markup.button.callback('➡','ucf_countries_'+server+'_'+(page+1)+(query?'_'+enc(query):'')));if(nav.length)rows.push(nav);rows.push([Markup.button.callback('🔎 Search Country','ucf_sc_'+server),Markup.button.callback('🔎 Search Service','ucf_ss_'+server)]);rows.push([Markup.button.callback('⬅ Servers','ns_user_menu')]);return bot.telegram.editMessageText(q.message.chat.id,q.message.message_id,undefined,'🌍 Select Country\n\n'+(query?'🔎 '+query+'\n\n':'')+'Page '+page+'/'+tot,Markup.inlineKeyboard(rows))}
async function services(bot,q,server,cid,page=1,query=''){const c=await refresh(server),co=c.countries.find(x=>String(x.id)===String(cid));if(!co)return;const a=filt(c.services,query),tot=Math.max(1,Math.ceil(a.length/6));page=Math.max(1,Math.min(page,tot));const rows=a.slice((page-1)*6,page*6).map(x=>[Markup.button.callback('📦 '+x.name,'ns_buy_'+server+'_'+enc(co.id)+'_'+enc(x.id))]);const nav=[];if(page>1)nav.push(Markup.button.callback('⬅','ucf_services_'+server+'_'+enc(co.id)+'_'+(page-1)+(query?'_'+enc(query):'')));if(page<tot)nav.push(Markup.button.callback('➡','ucf_services_'+server+'_'+enc(co.id)+'_'+(page+1)+(query?'_'+enc(query):'')));if(nav.length)rows.push(nav);rows.push([Markup.button.callback('🔎 Search Country','ucf_sc_'+server),Markup.button.callback('🔎 Search Service','ucf_ss_'+server+'_'+enc(co.id))]);rows.push([Markup.button.callback('⬅ Countries','ucf_countries_'+server+'_1')]);return bot.telegram.editMessageText(q.message.chat.id,q.message.message_id,undefined,'📦 Select Service\n\n🌍 '+co.name+'\n\n'+(query?'🔎 '+query+'\n\n':'')+'Page '+page+'/'+tot,Markup.inlineKeyboard(rows))}
const old=Telegraf.prototype.handleUpdate;Telegraf.prototype.handleUpdate=async function(u,...args){try{const q=u?.callback_query,uid=q?.from?.id,cb=q?.data||'';if(uid&&(cb==='ns_user_5sim'||cb==='ns_user_vak')){try{await this.telegram.answerCbQuery(q.id)}catch{};return countries(this,q,cb==='ns_user_5sim'?'5sim':'vak',1,'')}let m=cb.match(/^ucf_countries_(5sim|vak)_(\d+)(?:_(.*))?$/);if(uid&&m){try{await this.telegram.answerCbQuery(q.id)}catch{};return countries(this,q,m[1],+m[2],m[3]?dec(m[3]):'')}m=cb.match(/^ucf_country_(5sim|vak)_(.*)$/);if(uid&&m){try{await this.telegram.answerCbQuery(q.id)}catch{};return services(this,q,m[1],dec(m[2]),1,'')}m=cb.match(/^ucf_services_(5sim|vak)_(.*)_(\d+)(?:_(.*))?$/);if(uid&&m){try{await this.telegram.answerCbQuery(q.id)}catch{};return services(this,q,m[1],dec(m[2]),+m[3],m[4]?dec(m[4]):'')}m=cb.match(/^ucf_s([cs])_(5sim|vak)(?:_(.*))?$/);if(uid&&m){st.set(String(uid),{type:m[1]==='c'?'country':'service',server:m[2],country:m[3]?dec(m[3]):null});try{await this.telegram.answerCbQuery(q.id)}catch{};return this.telegram.sendMessage(uid,m[1]==='c'?'🔎 Search Country\n\nSend country name or ID:':'🔎 Search Service\n\nSend service name or ID:')}if(u.message?.chat?.type==='private'&&u.message.text&&!u.message.text.startsWith('/')&&st.has(String(u.message.from?.id))){const id=String(u.message.from.id),s=st.get(id);st.delete(id);const c=await refresh(s.server),a=filt(s.type==='country'?c.countries:c.services,u.message.text.trim());if(s.type==='country'){const rows=a.slice(0,20).map(x=>[Markup.button.callback('🌍 '+x.name,'ucf_country_'+s.server+'_'+enc(x.id))]);rows.push([Markup.button.callback('🔎 Search Again','ucf_sc_'+s.server)]);return this.telegram.sendMessage(id,'🌍 Country Search\n\nFound: '+a.length,Markup.inlineKeyboard(rows))}const rows=a.slice(0,20).map(x=>[Markup.button.callback('📦 '+x.name,s.country?'ns_buy_'+s.server+'_'+enc(s.country)+'_'+enc(x.id):'ucf_ss_'+s.server)]);rows.push([Markup.button.callback('🔎 Search Again','ucf_ss_'+s.server+(s.country?'_'+enc(s.country):''))]);return this.telegram.sendMessage(id,'📦 Service Search\n\nFound: '+a.length,Markup.inlineKeyboard(rows))}}catch(e){console.log('USER CATALOG SEARCH FIX:',e.message)}return old.call(this,u,...args)};
