const mongoose=require('mongoose');
const axios=require('axios');
const {Telegraf,Markup}=require('telegraf');
const VAK_KEY=process.env.VAKSMS_API_KEY||'';
const VAK_BASE='https://vak-sms.com/stubs/handler_api.php';
const states=new Map();
const schema=new mongoose.Schema({server:{type:String,unique:true},countries:{type:Array,default:[]},services:{type:Array,default:[]},operators:{type:Array,default:[]},markup:{type:Number,default:0}},{collection:'number_server_configs'});
const Config=mongoose.models.VakUserCatalogFinalConfig||mongoose.model('VakUserCatalogFinalConfig',schema);
async function cfg(){return Config.findOneAndUpdate({server:'vak'},{server:'vak'},{upsert:true,new:true,setDefaultsOnInsert:true});}
function enc(x){return encodeURIComponent(String(x));}function dec(x){try{return decodeURIComponent(x)}catch{return String(x)}}
async function vak(action,params={}){try{return (await axios.get(VAK_BASE,{params:{action,api_key:VAK_KEY,...params},timeout:12000})).data}catch{return null}}
function filter(a,q){const s=String(q||'').toLowerCase();return a.filter(x=>!s||String(x.name||'').toLowerCase().includes(s)||String(x.id||'').toLowerCase().includes(s)||String(x.code||'').toLowerCase().includes(s));}
async function rate(){try{const d=await mongoose.connection.db.collection('settings').findOne({key:'usdtInrRate'});const n=Number(d?.value);return Number.isFinite(n)&&n>0?n:100}catch{return 100}}
async function live(country,service){const d=await vak('getPrices',{country,service});let b=d?.[country]?.[service]||d?.[service]?.[country];if(!b){let f=null;const w=(o,n=0)=>{if(f||!o||typeof o!=='object'||n>6)return;if(o[country]?.[service]){f=o[country][service];return}if(o[service]?.[country]){f=o[service][country];return}Object.values(o).forEach(v=>{if(v&&typeof v==='object')w(v,n+1)})};w(d);b=f}let price=null,stock=0;const s=v=>{if(!v||typeof v!=='object')return;if(Array.isArray(v)){v.forEach(s);return}for(const k of ['cost','price','rate','sell_price','buy_price']){const n=Number(v[k]);if(Number.isFinite(n)&&n>0)price=price==null?n:Math.min(price,n)}for(const k of ['count','stock','qty','quantity','available','available_count']){const n=Number(v[k]);if(Number.isFinite(n)&&n>=0)stock+=n}Object.values(v).forEach(x=>{if(x&&typeof x==='object')s(x)})};s(b);return{price,stock}}
async function showCountries(bot,q,page=1,query=''){const c=await cfg(),a=filter(c.countries,query),total=Math.max(1,Math.ceil(a.length/5));page=Math.min(Math.max(1,page),total);const rows=a.slice((page-1)*5,page*5).map(x=>[Markup.button.callback(`🌍 ${x.name}`,`vuf_country_${enc(x.id)}`)]);const nav=[];if(page>1)nav.push(Markup.button.callback('⬅',`vuf_countries_${page-1}${query?'_'+enc(query):''}`));if(page<total)nav.push(Markup.button.callback('➡',`vuf_countries_${page+1}${query?'_'+enc(query):''}`));if(nav.length)rows.push(nav);rows.push([Markup.button.callback('🔎 Search Country','vuf_search_country'),Markup.button.callback('🔎 Search Service','vuf_search_service')]);rows.push([Markup.button.callback('⬅ Servers','ns_user_menu')]);return bot.telegram.editMessageText(q.message.chat.id,q.message.message_id,undefined,`🌍 Select Country\n\n${query?`🔎 ${query}\n\n`:''}Page ${page}/${total}`,Markup.inlineKeyboard(rows))}
async function showServices(bot,q,countryId,page=1,query=''){const c=await cfg(),co=c.countries.find(x=>String(x.id)===String(countryId));if(!co)return;const a=filter(c.services,query),total=Math.max(1,Math.ceil(a.length/5)),r=await rate(),rows=[];for(const x of a.slice((page-1)*5,page*5)){const z=await live(co.id,x.id);let sell=Number(x.price||0);if(sell<=0&&z.price!=null)sell=Math.ceil(z.price*r*(1+Number(c.markup||0)/100));const liveText=z.price!=null?` • Live ₹${Math.ceil(z.price*r)}`:'';rows.push([Markup.button.callback(`📦 ${x.name} • ₹${sell||0}${liveText} • Stock: ${z.stock}`,`ns_buy_vak_${enc(co.id)}_${enc(x.id)}`.replace('ns_buy_vak_','ns_buy_vak_'))])}const nav=[];if(page>1)nav.push(Markup.button.callback('⬅',`vuf_services_${enc(co.id)}_${page-1}${query?'_'+enc(query):''}`));if(page<total)nav.push(Markup.button.callback('➡',`vuf_services_${enc(co.id)}_${page+1}${query?'_'+enc(query):''}`));if(nav.length)rows.push(nav);rows.push([Markup.button.callback('🔎 Search Country','vuf_search_country'),Markup.button.callback('🔎 Search Service',`vuf_search_service_${enc(co.id)}`)]);rows.push([Markup.button.callback('⬅ Countries','vuf_countries_1')]);return bot.telegram.editMessageText(q.message.chat.id,q.message.message_id,undefined,`📦 Select Service\n\n🌍 ${co.name}\n\n${query?`🔎 ${query}\n\n`:''}Page ${page}/${total}`,Markup.inlineKeyboard(rows))}
const previous=Telegraf.prototype.handleUpdate;
Telegraf.prototype.handleUpdate=async function(update,...args){try{const q=update?.callback_query,uid=q?.from?.id,cb=q?.data||'';if(uid&&cb==='ns_user_vak'){try{await this.telegram.answerCbQuery(q.id)}catch{};return showCountries(this,q,1,'')}if(uid&&cb==='vuf_search_country'){states.set(String(uid),{type:'country'});try{await this.telegram.answerCbQuery(q.id)}catch{};return this.telegram.sendMessage(uid,'🔎 Search Country\n\nSend country name, ID or code:')}if(uid&&cb.startsWith('vuf_search_service')){const p=cb.split('_');states.set(String(uid),{type:'service',country:p[3]?dec(p[3]):null});try{await this.telegram.answerCbQuery(q.id)}catch{};return this.telegram.sendMessage(uid,'🔎 Search Service\n\nSend service name or ID:')}let m=cb.match(/^vuf_countries_(\d+)(?:_(.*))?$/);if(uid&&m){try{await this.telegram.answerCbQuery(q.id)}catch{};return showCountries(this,q,Number(m[1]),m[2]?dec(m[2]):'')}m=cb.match(/^vuf_country_(.*)$/);if(uid&&m){try{await this.telegram.answerCbQuery(q.id)}catch{};return showServices(this,q,dec(m[1]),1,'')}m=cb.match(/^vuf_services_(.*)_(\d+)(?:_(.*))?$/);if(uid&&m){try{await this.telegram.answerCbQuery(q.id)}catch{};return showServices(this,q,dec(m[1]),Number(m[2]),m[3]?dec(m[3]):'')}if(uid&&update.message?.chat?.type==='private'&&update.message.text&&!update.message.text.startsWith('/')&&states.has(String(uid))){const st=states.get(String(uid));states.delete(String(uid));const text=update.message.text.trim(),c=await cfg();if(st.type==='country'){const a=filter(c.countries,text),rows=a.slice(0,10).map(x=>[Markup.button.callback(`🌍 ${x.name}`,`vuf_country_${enc(x.id)}`)]);rows.push([Markup.button.callback('🔎 Search Again','vuf_search_country')],[Markup.button.callback('⬅ Servers','ns_user_vak')]);return this.telegram.sendMessage(uid,`🌍 Country Search\n\n🔎 ${text}\n\nFound: ${a.length}`,Markup.inlineKeyboard(rows))}if(st.type==='service'&&st.country){const a=filter(c.services,text),rows=[];for(const x of a.slice(0,10)){const z=await live(st.country,x.id),r=await rate();let sell=Number(x.price||0);if(sell<=0&&z.price!=null)sell=Math.ceil(z.price*r*(1+Number(c.markup||0)/100));rows.push([Markup.button.callback(`📦 ${x.name} • ₹${sell||0} • Stock: ${z.stock}`,`ns_buy_vak_${enc(st.country)}_${enc(x.id)}`)])}rows.push([Markup.button.callback('🔎 Search Again',`vuf_search_service_${enc(st.country)}`)],[Markup.button.callback('⬅ Countries','vuf_countries_1')]);return this.telegram.sendMessage(uid,`📦 Service Search\n\n🔎 ${text}\n\nFound: ${a.length}`,Markup.inlineKeyboard(rows))}}}catch(e){console.log('VAK USER CATALOG FINAL:',e.message)}return previous.call(this,update,...args)};
